from pathlib import Path
import json,hashlib,subprocess,shutil
base=Path('.context/placid-badger-cad-second-half/runtime-resume-2026-10-02');s=base/'ios-uninterrupted';cleanup=json.loads((s/'cleanup-verification.json').read_text());assert all(cleanup[k] for k in ['simulatorDeleted','derivedDataDeleted','resultBundleDeleted','testResultBundleDeleted']);monitor=json.loads((s/'boot-monitor-summary.json').read_text());assert monitor['readyForVisualApproval'] is False
processes=json.loads((s/'helper-descendants-before-cleanup.json').read_text());checks=[]
for item in processes:
 p=subprocess.run(['rtk','proxy','ps','-p',str(item['pid']),'-o','pid=,ppid=,comm='],capture_output=True,timeout=5);checks.append({'pid':item['pid'],'before':item['identity'],'after':p.stdout.decode().strip(),'absent':not p.stdout.strip()})
(s/'helper-cleanup-verification.json').write_text(json.dumps(checks,indent=2)+'\n');assert all(x['absent'] for x in checks),checks
h=s/'harness';h.mkdir(exist_ok=False)
for name in ['lifecycle.zsh','boot-uninterrupted.py','bounded-command.py','source-gate.py','build-parity.py']:shutil.copyfile(base/'prep'/name,h/name)
record={'boardID':'zlagboard.pro','runtime':'iOS26.5','owner':'placid-badger-cad-second-half','status':'BLOCKED before build/install: one uninterrupted900s first boot remained in AddressBook migration and never reached Home AX.','appWorkflowPassed':False,'readyForHumanGeometryReview':False,'humanAccepted':False,'humanAcceptance':'Pending; fresh app review gate unmet.','buildAttempted':False,'installAttempted':False,'testsRun':0,'contactCoverage':{'required':28,'captured':0},'workoutAttempted':False,'boot':monitor,'rawBoot':'boot-uninterrupted.log','readinessProbes':'readiness-commands.json','startupScreen':'startup-after-eight-minutes.png','migrationDiagnostic':{'command':'migration-diagnostic-command.json','raw':'migration-diagnostic-command.stdout','result':'Bounded exact-device filtered query succeeded but returned only the header. No progress or stuck-RPC conclusion follows.'},'sourceGate':'No Home screenshot candidate or visual approval was produced; clean-HEAD build gate never opened. No app/package/shared-service changes.','cleanup':cleanup,'helperCleanup':'helper-cleanup-verification.json','priorEvidence':'Original26.4/26.5 startup failures and two successful fresh builds remain retained separately under zlagboard-pro; this attempt did not rebuild or supersede them.','interpretation':'Longer uninterrupted first boot did not resolve startup within its bound. No root cause is proven; no further attempt or private/shared-service repair was performed.'}
(s/'final-runtime-validation.json').write_text(json.dumps(record,indent=2)+'\n');files={str(p.relative_to(s)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(s.rglob('*')) if p.is_file()};inventory=base/'ios-uninterrupted.sha256.json';inventory.write_text(json.dumps(files,indent=2)+'\n');print(json.dumps({'tree':str(s),'inventoryOutsideTree':str(inventory),'files':len(files),'aggregateSHA256':files['final-runtime-validation.json'],'cleanup':cleanup,'helperProcessesAbsent':all(x['absent'] for x in checks)},indent=2))
