from pathlib import Path
import sys,json,hashlib,math
from marker_correlations import audit
p=Path(sys.argv[1]);read=lambda name:json.loads((p/name).read_text());release=read('runtime-release.json')
schemaRaw=Path(release['markerSchemaPath']).read_bytes();assert hashlib.sha256(schemaRaw).hexdigest()==release['markerSchemaSHA256'];schema=json.loads(schemaRaw);assert schema['reviewed']
commands=read('commands.json');copy=read('trace-copy.json');end=read('observation-end.json');env=read('launch-review-environment.json');binary=read('installed-binary-gate.json');readiness=read('train-startup-readiness.json')
raws=[f.read_bytes() for f in sorted(p.glob('events-*.jsonl'))];rows=[json.loads(l) for raw in raws for l in raw.splitlines(keepends=True) if l.endswith(b'\n')];finite=lambda x:type(x) in (int,float) and math.isfinite(x)
anchor=read('appearance-anchor.json') if (p/'appearance-anchor.json').exists() else None;target=anchor['endEpoch'] if anchor else None
# Early failure censors at actual observation end, never at a future intended endpoint.
censor=min(target,end['epoch']) if target is not None else end['epoch'];correlation=audit(rows,schema,censor)
appears=[r for r in rows if r['event']=='workout-probe-appear-before-autostart' and r['epoch']<=censor]
expectedRaw=Path(release['priorActionEnvironmentPath']).read_bytes();assert hashlib.sha256(expectedRaw).hexdigest()==release['priorActionEnvironmentSHA256'];expected=json.loads(expectedRaw);expected['HANGTEN_REVIEW_DIAGNOSTIC_RUN']='placid-badger-cad-second-half-startup-observation-action';expected['HANGTEN_REVIEW_STARTUP_OBSERVATION']='1'
checks=dict(exactEnvironment=env==expected,binaryBound=binary['sha256']==release['binarySHA256'],completeJSONL=bool(raws) and all(raw.endswith(b'\n') for raw in raws),completeContiguous=bool(rows) and all(r['complete'] for r in rows) and [r['sequence'] for r in rows]==list(range(1,len(rows)+1)),traceCopiesExact=all(hashlib.sha256(Path(x['copy']).read_bytes()).hexdigest()==x['sha256'] for x in copy['copies']),allRecordTimesFinite=all(finite(r.get('epoch')) and finite(r.get('uptime')) for r in rows),correlationUnambiguous=not correlation['errors'],atMostOneContextAndAppearance=len(correlation['contexts'])<=1 and len(appears)<=1,commandIntervalsFinite=all(finite(c.get('startEpoch')) and finite(c.get('endEpoch')) and c['endEpoch']>=c['startEpoch'] for c in commands))
completeness=dict(trainReadiness=readiness['passed'],exactlyOneAppearance=len(appears)==1,oneContext=len(correlation['contexts'])==1,appearanceTimely=anchor is not None and not anchor['observedAfterArrivalDeadline'],fixedAnchor=anchor is not None and abs(anchor['endEpoch']-anchor['record']['epoch']-30)<1e-6,normalWindowEnd=end['reason']=='fixed-appearance-plus30',reachedDeadline=target is not None and end['epoch']>=target,requiredMarkersPresent=all(any(r['event']==e for r in correlation['markers']) for e in schema['requiredEvents']),noCommandTimeout=not any(c.get('timeout') or c.get('interrupted') for c in commands))
wellformed=all(checks.values());complete=all(completeness.values())
report=dict(evidenceWellFormed=wellformed,observationWindowComplete=complete,completeObservationPassed=wellformed and complete,evidenceChecks=checks,windowChecks=completeness,correlation=correlation,windowEnd=end,actualCensorEpoch=censor,commands=commands,recordsAfterObservationEnd=[r['sequence'] for r in rows if r['epoch']>censor],limits=['Well-formed partial evidence is not a complete30second observation PASS.','A right-censored span has no observed endpoint within the bounded interval; completion events are not forced.','Scalar context/map validity does not itself imply a nonnull attempt or completion.','Task sleep catch is the existing error path, not independent proof of cancellation cause.','Load-return/ready UUIDs link to model constructor identity; no actual rendered Scene/GPU identity is inferred.','No completed load event means its model link remains unknown, not assigned by order.','Asynchronous external polling of the same initial screenshot is a method change alongside source instrumentation.','No color,12frame,main-thread-blockage,or production-fix claim.'])
out=p/'startup-observation-validation.json';assert not out.exists();out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(dict(evidenceWellFormed=wellformed,observationWindowComplete=complete),indent=2));assert wellformed and complete
