from pathlib import Path
import json,hashlib
p=Path('.context/placid-badger-cad-second-half/pr-readiness-repair-2026-10-02/evo');load=lambda f:json.loads(f.read_text());sha=lambda f:hashlib.sha256(f.read_bytes()).hexdigest()
runs=[]
for arm,session in [('on',30458),('off',60276)]:
 d=p/('strict-hands-'+arm+'-landscape');a=load(d/'structural-correspondence.json');h=load(d/'hand-lifetime-validation.json');v=load(d/'visual-review.json')
 frames=sorted({tuple(host['frameInWindow']) for r in h['boardFrameHistory'] for host in r['boardHosts']})
 cameras=sorted({tuple(r['cameraTransform']) for r in h['boardFrameHistory'] if r['cameraTransform']});roots=sorted({tuple(r['rootTransform']) for r in h['boardFrameHistory'] if r['rootTransform']})
 (d/'capture-process-status.json').write_text(json.dumps({'execSessionID':session,'observedExitStatus':0,'captures':12,'noRepeat':True},indent=2)+'\n')
 runs.append({'arm':arm,'directory':str(d),'records':a['traceRecords'],'checks':a['checks'],'handChecks':h['checks'],'finalHandCounts':h['finalCounts'],'actualPhaseIntervals':a['actualPhaseIntervals'],'visualFailureReproduced':v['visualFailureReproduced'],'visualReviewSHA256':sha(d/'visual-review.json'),'observedBoardColors':[r['observedBoardColor'] for r in v['captures']],'actualBoardFrameSet':frames,'cameraTransformSet':cameras,'rootTransformSet':roots})
failedOff=runs[1]['visualFailureReproduced']
r={'scope':'One same-binary fresh direct-root hands-ON control and one strict hands-OFF natural workout. No thirdarm/repeat/productionfix.','binarySHA256':load(p/'strict-hand-suppression-code-parity/mach-o-parity.json')['builtMachO']['HangTen.debug.dylib']['sha256'],'sourcePatchSHA256':sha(p/'strict-hand-suppression-applied/applied.patch'),'runs':runs,'validBoth':all(all(x['checks'].values()) and all(x['handChecks'].values()) for x in runs),'sameActualFrameSet':runs[0]['actualBoardFrameSet']==runs[1]['actualBoardFrameSet'],'sameCameraTransformSet':runs[0]['cameraTransformSet']==runs[1]['cameraTransformSet'],'sameRootTransformSet':runs[0]['rootTransformSet']==runs[1]['rootTransformSet'],'environments':load(p/'strict-hand-suppression-environments.json'),'finalParity':load(p/'strict-hand-suppression-final-parity.json'),'interpretation':('Observed failure persists with zero app hand constructor/make entries from recorder opening through final retained marker. Those hand scene/host entries are not necessary for this observed direct-root failure; suppression is insufficient.' if failedOff else 'Observed ON failure and OFF success form a single controlled contrast with zero OFF hand entries. This onepair does not establish causal mechanism or a production fix; instrumentation and runvariance remain limitations.'),'workoutIssueResolved':False,'productionFix':False,'limitations':['All24 measured wholeimages directly reviewed, without crops or pixel measurement.','Onepair only; no assertion of universal necessity/sufficiency or exact recovery instant between captures.','Counter coverage is the two app scene constructors and two make entries through retained tail, not all framework GPU activity or future lifetime.','Natural rest uses sparse boundary census after120s sampler ends; no continuous middle-rest visualclaim.','Observed actual frame/transform sets are compared; no layout compensation introduced.'],'handoff':{'sourceRuntimeDD':'Returned to root after final evidence freeze','uuid':'BDCA0D77-94C2-4A97-900B-443F75C64691','controller':90373,'resources':'Existing registered resources remain live; no new external resources or cleanup.'}}
f=p/'strict-hand-suppression-findings.json';assert not f.exists();f.write_text(json.dumps(r,indent=2)+'\n');print({'report':str(f),'sha256':sha(f),'validBoth':r['validBoth'],'offFailure':failedOff,'sameActualFrameSet':r['sameActualFrameSet'],'sameCameraTransformSet':r['sameCameraTransformSet']})
