from pathlib import Path
import json,hashlib
p=Path('.context/placid-badger-cad-second-half/pr-readiness-repair-2026-10-02/evo')
sha=lambda f:hashlib.sha256(f.read_bytes()).hexdigest()
load=lambda f:json.loads(f.read_text())
runs=[]
for arm in ['short','long']:
 d=p/('standalone-timing-'+arm);v=load(d/'timing-validation.json');im=load(d/'visual-review.json');s=load(d/'schedule.json');trace=load(d/'trace-copy.json')
 runs.append({'arm':arm,'directory':str(d),'durations':s['phaseDurations'],'starts':s['phaseStartOffsets'],'totalSeconds':s['totalDuration'],'tailSeconds':s['completionTailOffset'],'recordCount':trace['records'],'captureCount':len(v['captures']),'allChecksPassed':all(v['checks'].values()),'checks':v['checks'],'visualPassed':im['all20MatchViewedCorrectStates'],'directlyViewedImages':im['referencesDirectlyViewed'],'visualMethod':im['method'],'actualMutationOffsets':[x['epoch']-s['baseEpoch'] for x in v['intendedAndMutationEvents'] if x['event']=='highlight-after'],'validationSHA256':sha(d/'timing-validation.json'),'visualReviewSHA256':sha(d/'visual-review.json'),'maximumScreenshotStartLag':max(x['startDelayFromTarget'] for x in v['captures'])})
r={'scope':'Two bounded DEBUG standalone E timing arms, one each on same binary; no production fix or training plan changes.','runs':runs,'bothArmsPassed':all(x['allChecksPassed'] and x['visualPassed'] for x in runs),'interpretation':'If both arms pass, increasing isolated preview from8 to180seconds alone was insufficient to reproduce the actual workout color defect in these runs. This does not establish that duration is irrelevant in the full workout context, and does not prove any GPU sleep or host mechanism.','workoutIssueResolved':False,'productionFix':False,'humanAcceptanceClaim':False,'binary':load(p/'standalone-timing-code-parity/mach-o-parity.json')['builtMachO']['HangTen.debug.dylib']['sha256'],'finalParity':load(p/'standalone-timing-final-parity.json'),'environmentComparison':load(p/'standalone-timing-environment-comparison.json'),'sourcePatchSHA256':sha(p/'standalone-timing-applied/applied.patch'),'retainedFailure':{'path':str(p/'standalone-timing-short/validator-first.stderr'),'cause':'Validator treated sparse surface-inputs event as full scene snapshot; corrected record-type filter only, independently reviewed. No runtime or source rerun.','correctionPatch':str(p/'standalone-timing-applied/validator-record-type-correction.patch')},'limitations':['Five whole +5 images directly viewed perarm; other15 judged through whole-file byte equality, not individual opening.','Sparse census and snapshots cover boundaries and first6.75seconds perphase plus tail; middle long-rest visualstate not continuously observed.','Long arm also has greater process age by nextactive; one run perarm cannot establish variance or universal causality.','No AX/touch/input/counter/sampler/hand/navigation gates used; manual buttons remain unused.'],'resourceHandoff':{'uuid':'BDCA0D77-94C2-4A97-900B-443F75C64691','controller':90373,'newExternalResources':False,'cleanup':'Existing registered resources remain live for root; no cleanup or further run performed.'}}
f=p/'standalone-timing-findings.json';assert not f.exists();f.write_text(json.dumps(r,indent=2)+'\n');print({'bothArmsPassed':r['bothArmsPassed'],'report':str(f),'sha256':sha(f)})
