from pathlib import Path
import sys,json,hashlib
p=Path('.context/placid-badger-cad-second-half/pr-readiness-repair-2026-10-02/evo')/sys.argv[1]
rs=[json.loads(l) for f in p.glob('events-*.jsonl') for l in f.read_text().splitlines()];schedule=json.loads((p/'schedule.json').read_text());base=schedule['baseEpoch'];measured=[r for r in rs if r['epoch']>=base];scenes=[r for r in measured if 'sceneLifecycleToken'in r and 'cachedMode'in r];census=[r['applicationCensus'] for r in measured if 'applicationCensus'in r];env=json.loads((p/'launch-review-environment.json').read_text());counter=env.get('HANGTEN_REVIEW_SCENE_UPDATE_COUNTER')=='1'
checks={'oneMakeWholeRun':sum(r['event']=='view-make' for r in rs)==1,'oneScene':len({r['sceneLifecycleToken'] for r in scenes})==1,'oneView':len({r['viewToken'] for r in scenes if 'viewToken'in r})==1,'initialViewportCorrect':schedule['actualViewportPoints']==([410,410*120/700] if env['HANGTEN_REVIEW_STANDALONE_DRIVER'] in ['F','G'] else [210,36]),'stableViewportAfterFirstTransition':all(r['viewportPoints']==[210,36] for r in scenes if r['epoch']>=base+9),'appActiveDuringMeasurement':all(c['applicationState']==0 for c in census),'windowActiveDuringMeasurement':all(any(s['activationState']==0 and any(w['key'] and not w['hidden'] and w['alpha']==1 for w in s['windows']) for s in c['windowScenes']) for c in census),'rootAndCameraActive':all(r['boardRenderMembership']['rootActive'] and r['boardRenderMembership']['cameraActive'] for r in scenes),'noPeriodicSampler':not any(r['event']=='sample' for r in rs),'noSecondHost':not any('secondHost'in r for r in rs),'counterPresenceCorrect':all(('sceneUpdateCount'in r)==counter for r in scenes),'scriptComplete':any(r['event']=='standalone-script-complete' for r in rs)}
brackets=[]
for c in json.loads((p/'captures.json').read_text()):
 pre=[r for r in scenes if r['epoch']<=c['startEpoch']];post=[r for r in scenes if r['epoch']>=c['endEpoch']];before=pre[-1] if pre else None;after=post[0] if post else None
 expected='preview' if c['phase']=='preview' else 'active';ids=[] if c['phase']=='clear' else ['edge-20-left','edge-20-right']
 valid=before is not None and after is not None and all(r['cachedMode']==expected and r['selectedIDs']==ids for r in [before,after])
 brackets.append(dict(c,bracketPassed=valid,priorRecord=before,afterRecord=after,startDelayFromTarget=c['startEpoch']-c['targetEpoch']))
checks['all20Brackets']=len(brackets)==20 and all(c['bracketPassed'] for c in brackets)
counts=[r['sceneUpdateCount'] for r in scenes if 'sceneUpdateCount'in r]
out={'checks':checks,'measurementBaseEpoch':base,'counterEnabled':counter,'counterRange':[min(counts),max(counts)] if counts else None,'captures':brackets,'requestedAndMutationEvents':[r for r in rs if r['event'].startswith('standalone-intended') or r['event']in ['standalone-observed-selection','surface-inputs','highlight-before','highlight-after']]};target=p/'structural-validation.json';assert not target.exists();target.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'checks':checks,'counterRange':out['counterRange'],'maxScreenshotStartLag':max(c['startDelayFromTarget'] for c in brackets)},indent=2));assert all(checks.values())
