"""Canonical hangboard package and onboarding run manifest tooling."""

from __future__ import annotations

from dataclasses import dataclass, replace
import json
import re
from pathlib import Path
import shutil
from typing import Any, Mapping


_CATALOG_SCHEMA_VERSION = 1
_BOARD_SCHEMA_VERSION = 1
_LIFECYCLES = ("draft", "onboarding", "approved", "shipped")
_IDENTIFIER = re.compile(r"^[a-z0-9]+(?:[a-z0-9._-]*[a-z0-9])?$")
_FINGER_WORDS = {"1": "one", "2": "two", "3": "three", "4": "four"}
_SWIFT_HOLD_KINDS = frozenset({"jug", "edge", "pocket", "sloper"})
_SWIFT_GRIP_TYPES = frozenset(
    {
        "openHand",
        "halfCrimp",
        "fullCrimp",
        "fourFingerPocket",
        "threeFingerPocket",
        "twoFingerPocket",
        "sloper",
    }
)
_SWIFT_HOLD_FEATURES = frozenset(
    {
        "jug",
        "roundSloper",
        "largeSlope",
        "largeEdge",
        "mediumEdge",
        "smallEdge",
        "pocket",
        "twoFingerPocket",
        "threeFingerPocket",
        "fourFingerPocket",
        "fourFingerFlatEdge",
        "fourFingerIncutEdge",
    }
)
_SWIFT_HEADER = """// Generated by scripts/export-board-catalog.py from Hangboards/catalog.json.
// Do not edit by hand.

import Foundation
import SwiftUI
"""
_SWIFT_BOARD_OVERRIDES: dict[str, dict[str, str | None]] = {
    "metolius.wood-grips-compact-ii": {
        "staticName": "compactII",
        "subtitle": "A compact FSC-certified wood board for everyday strength work.",
        "photoAssetName": "CompactBoardIllustration",
    }
}


@dataclass
class CatalogBoardEntry:
    id: str
    path: str
    lifecycle: str

    @classmethod
    def from_json(cls, payload: Mapping[str, Any], source: str) -> "CatalogBoardEntry":
        board_id = _required_str(payload, "id", f"{source}.id")
        board_path = _required_str(payload, "path", f"{source}.path")
        lifecycle = _required_str(payload, "lifecycle", f"{source}.lifecycle")
        if lifecycle not in _LIFECYCLES:
            raise ValueError(
                f"{source}.lifecycle must be one of {_LIFECYCLES}, got {lifecycle!r}"
            )
        _require_identifier(board_id, "board id")
        if board_path.startswith("/") or ".." in Path(board_path).parts:
            raise ValueError(f"{source}.path must be a relative path inside the catalog")
        return cls(board_id, board_path, lifecycle)

    def to_json(self) -> dict[str, object]:
        return {"id": self.id, "path": self.path, "lifecycle": self.lifecycle}


@dataclass
class CatalogDocument:
    boards: list[CatalogBoardEntry]
    schema_version: int = _CATALOG_SCHEMA_VERSION

    @classmethod
    def from_json(
        cls, payload: Mapping[str, Any], source: str
    ) -> "CatalogDocument":
        schema_version = _required_int(payload, "schemaVersion", f"{source}.schemaVersion")
        if schema_version != _CATALOG_SCHEMA_VERSION:
            raise ValueError(
                f"{source}.schemaVersion must be {_CATALOG_SCHEMA_VERSION}, got {schema_version!r}"
            )
        entries = _required_list(payload, "boards", f"{source}.boards")
        parsed = [
            CatalogBoardEntry.from_json(raw, f"{source}.boards[{index}]")
            for index, raw in enumerate(entries)
        ]
        return cls(boards=parsed, schema_version=schema_version)

    def to_json(self) -> dict[str, object]:
        return {
            "schemaVersion": self.schema_version,
            "boards": [board.to_json() for board in self.boards],
        }


@dataclass
class BoardHoldFrame:
    x: float
    y: float
    width: float
    height: float

    @classmethod
    def from_json(cls, payload: Mapping[str, Any], source: str) -> "BoardHoldFrame":
        return cls(
            x=_required_float(payload, "x", f"{source}.x"),
            y=_required_float(payload, "y", f"{source}.y"),
            width=_required_float(payload, "width", f"{source}.width"),
            height=_required_float(payload, "height", f"{source}.height"),
        )

    def to_json(self) -> dict[str, float]:
        return {
            "x": self.x,
            "y": self.y,
            "width": self.width,
            "height": self.height,
        }


@dataclass
class BoardHold:
    id: str
    name: str
    short_label: str
    detail: str
    kind: str
    frame: BoardHoldFrame
    region_id: int | None = None
    size_mm: int | None = None
    grip_type: str | None = None
    features: tuple[str, ...] = ()

    @classmethod
    def from_json(cls, payload: Mapping[str, Any], source: str) -> "BoardHold":
        hold_id = _required_str(payload, "id", f"{source}.id")
        _require_identifier(hold_id, "hold id")
        name = _required_str(payload, "name", f"{source}.name")
        short_label = _required_str(payload, "shortLabel", f"{source}.shortLabel")
        detail = _required_str(payload, "detail", f"{source}.detail")
        kind = _required_str(payload, "kind", f"{source}.kind")
        if kind not in _SWIFT_HOLD_KINDS:
            raise ValueError(f"{source}.kind has unsupported Swift HoldKind {kind!r}")
        frame_raw = _required_mapping(payload, "frame", source)
        frame = BoardHoldFrame.from_json(frame_raw, f"{source}.frame")
        region_id = payload.get("regionId")
        parsed_region_id = (
            _required_int(payload, "regionId", f"{source}.regionId")
            if region_id is not None
            else None
        )
        if parsed_region_id is not None and parsed_region_id <= 0:
            raise ValueError(f"{source}.regionId must be positive")
        size_mm = payload.get("sizeMillimeters")
        if size_mm is not None and (not isinstance(size_mm, int) or size_mm <= 0):
            raise ValueError(f"{source}.sizeMillimeters must be a positive integer")
        grip_type = payload.get("gripType")
        if grip_type is not None and not isinstance(grip_type, str):
            raise ValueError(f"{source}.gripType must be a string")
        if grip_type is not None and grip_type not in _SWIFT_GRIP_TYPES:
            raise ValueError(f"{source}.gripType has unsupported Swift GripType {grip_type!r}")
        features_raw = payload.get("features", [])
        if not isinstance(features_raw, list):
            raise ValueError(f"{source}.features must be an array")
        features = tuple(
            _required_str({"value": value}, "value", f"{source}.features[{index}]")
            for index, value in enumerate(features_raw)
        )
        for feature in features:
            if feature not in _SWIFT_HOLD_FEATURES:
                raise ValueError(f"{source}.features has unsupported Swift HoldFeature {feature!r}")
        return cls(
            id=hold_id,
            name=name,
            short_label=short_label,
            detail=detail,
            kind=kind,
            frame=frame,
            region_id=parsed_region_id,
            size_mm=size_mm,
            grip_type=grip_type,
            features=features,
        )

    def to_json(self) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "id": self.id,
            "name": self.name,
            "shortLabel": self.short_label,
            "detail": self.detail,
            "kind": self.kind,
            "frame": self.frame.to_json(),
            "features": list(self.features),
        }
        if self.region_id is not None:
            payload["regionId"] = self.region_id
        if self.size_mm is not None:
            payload["sizeMillimeters"] = self.size_mm
        if self.grip_type is not None:
            payload["gripType"] = self.grip_type
        return payload


@dataclass
class OnboardingRun:
    id: str
    path: Path
    region_count: int
    lifecycle: str
    status: str

    @classmethod
    def from_json(
        cls,
        payload: Mapping[str, Any],
        source: str,
        *,
        board_root: Path,
    ) -> "OnboardingRun":
        run_id = _required_str(payload, "id", f"{source}.id")
        _require_identifier(run_id, "run id")
        path = _required_str(payload, "path", f"{source}.path")
        if path.startswith("/") or "\\" in path:
            raise ValueError(f"{source}.path must be a relative path")
        relative = Path(path)
        _require_relative_subpath(board_root, relative, f"{source}.path")
        region_count = _required_int(payload, "regionCount", f"{source}.regionCount")
        if region_count < 0:
            raise ValueError(f"{source}.regionCount must be non-negative")
        lifecycle = _required_str(payload, "lifecycle", f"{source}.lifecycle")
        if lifecycle not in _LIFECYCLES:
            raise ValueError(f"{source}.lifecycle must be one of {_LIFECYCLES}")
        status = _required_str(payload, "status", f"{source}.status")
        return cls(
            id=run_id,
            path=relative,
            region_count=region_count,
            lifecycle=lifecycle,
            status=status,
        )

    def to_json(self) -> dict[str, object]:
        return {
            "id": self.id,
            "path": self.path.as_posix(),
            "regionCount": self.region_count,
            "lifecycle": self.lifecycle,
            "status": self.status,
        }


@dataclass
class BoardDocument:
    id: str
    lifecycle: str
    holds: list[BoardHold]
    onboarding_runs: list[OnboardingRun]
    manufacturer: str | None = None
    name: str | None = None
    product_url: str | None = None
    dimensions: str | None = None
    aspect_ratio: float | None = None
    schema_version: int = _BOARD_SCHEMA_VERSION

    @classmethod
    def from_json(
        cls, payload: Mapping[str, Any], source: str, *, board_root: Path
    ) -> "BoardDocument":
        schema_version = _required_int(payload, "schemaVersion", f"{source}.schemaVersion")
        if schema_version != _BOARD_SCHEMA_VERSION:
            raise ValueError(
                f"{source}.schemaVersion must be {_BOARD_SCHEMA_VERSION}, got {schema_version!r}"
            )
        board_id = _required_str(payload, "id", f"{source}.id")
        _require_identifier(board_id, "board id")
        lifecycle = _required_str(payload, "lifecycle", f"{source}.lifecycle")
        if lifecycle not in _LIFECYCLES:
            raise ValueError(
                f"{source}.lifecycle must be one of {_LIFECYCLES}, got {lifecycle!r}"
            )
        holds_payload = _required_list(payload, "holds", f"{source}.holds")
        holds: list[BoardHold] = []
        for index, raw_hold in enumerate(holds_payload):
            if not isinstance(raw_hold, Mapping):
                raise ValueError(f"{source}.holds[{index}] must be an object")
            holds.append(BoardHold.from_json(raw_hold, f"{source}.holds[{index}]"))
        hold_ids = [hold.id for hold in holds]
        if len(hold_ids) != len(set(hold_ids)):
            raise ValueError("duplicate hold ids in board document")
        region_ids = [hold.region_id for hold in holds if hold.region_id is not None]
        if len(region_ids) != len(set(region_ids)):
            raise ValueError("duplicate hold regionIds in board document")

        onboarding_runs_payload = payload.get("onboardingRuns", [])
        if not isinstance(onboarding_runs_payload, list):
            raise ValueError(f"{source}.onboardingRuns must be an array")
        onboarding_runs: list[OnboardingRun] = []
        for index, raw_run in enumerate(onboarding_runs_payload):
            if not isinstance(raw_run, Mapping):
                raise ValueError(f"{source}.onboardingRuns[{index}] must be an object")
            onboarding_runs.append(
                OnboardingRun.from_json(
                    raw_run, f"{source}.onboardingRuns[{index}]", board_root=board_root
                )
            )
        run_ids = [run.id for run in onboarding_runs]
        if len(run_ids) != len(set(run_ids)):
            raise ValueError("duplicate onboarding run ids in board document")

        manufacturer = payload.get("manufacturer")
        if manufacturer is not None and not isinstance(manufacturer, str):
            raise ValueError(f"{source}.manufacturer must be a string when present")
        name = payload.get("name")
        if name is not None and not isinstance(name, str):
            raise ValueError(f"{source}.name must be a string when present")
        product_url = payload.get("productURL")
        if product_url is not None and not isinstance(product_url, str):
            raise ValueError(f"{source}.productURL must be a string when present")
        dimensions = payload.get("dimensions")
        if dimensions is not None and not isinstance(dimensions, str):
            raise ValueError(f"{source}.dimensions must be a string when present")
        aspect_ratio = payload.get("aspectRatio")
        if aspect_ratio is not None and not isinstance(aspect_ratio, (float, int)):
            raise ValueError(f"{source}.aspectRatio must be a number when present")

        return cls(
            id=board_id,
            lifecycle=lifecycle,
            holds=holds,
            onboarding_runs=onboarding_runs,
            manufacturer=manufacturer if manufacturer is not None else None,
            name=name if name is not None else None,
            product_url=product_url if product_url is not None else None,
            dimensions=dimensions if dimensions is not None else None,
            aspect_ratio=float(aspect_ratio) if aspect_ratio is not None else None,
            schema_version=schema_version,
        )

    def to_json(self) -> dict[str, object]:
        return {
            "schemaVersion": self.schema_version,
            "id": self.id,
            "manufacturer": self.manufacturer,
            "name": self.name,
            "productURL": self.product_url,
            "dimensions": self.dimensions,
            "aspectRatio": self.aspect_ratio,
            "lifecycle": self.lifecycle,
            "holds": [hold.to_json() for hold in self.holds],
            "onboardingRuns": [run.to_json() for run in self.onboarding_runs],
        }


def load_catalog(path: Path) -> CatalogDocument:
    payload = _load_json_payload(Path(path), "catalog")
    return CatalogDocument.from_json(payload, "catalog")


def load_board(path: Path) -> BoardDocument:
    board_path = Path(path)
    payload = _load_json_payload(board_path, "board")
    return BoardDocument.from_json(payload, "board", board_root=board_path.parent)


def validate_catalog(path: Path) -> CatalogDocument:
    catalog = load_catalog(path)
    catalog_root = Path(path).parent.resolve(strict=False)
    seen_ids: set[str] = set()
    seen_board_paths: set[Path] = set()
    for index, entry in enumerate(catalog.boards):
        if entry.id in seen_ids:
            raise ValueError(f"duplicate board id: {entry.id}")
        seen_ids.add(entry.id)
        _require_relative_subpath(catalog_root, Path(entry.path), f"catalog.boards[{index}].path")
        board_path = catalog_root / entry.path
        if board_path in seen_board_paths:
            raise ValueError(f"duplicate board path: {entry.path}")
        seen_board_paths.add(board_path)
        board = load_board(board_path)
        if board.id != entry.id:
            raise ValueError(
                f"board id in {entry.path!r} ({board.id!r}) does not match catalog id {entry.id!r}"
            )
        if board.lifecycle != entry.lifecycle:
            raise ValueError(
                f"board lifecycle mismatch for {entry.id!r}: catalog entry {entry.lifecycle!r} vs board {board.lifecycle!r}"
            )
    return catalog


def register_run(
    catalog_path: Path,
    board_id: str,
    run_path: Path,
    run_id: str | None = None,
) -> BoardDocument:
    catalog = validate_catalog(catalog_path)
    catalog_root = Path(catalog_path).parent.resolve(strict=False)
    board_entry = _find_board_entry(catalog, board_id)
    if board_entry is None:
        raise ValueError(f"board id not found: {board_id!r}")
    board_path = (catalog_root / board_entry.path).resolve(strict=False)
    board_root = board_path.parent
    board = load_board(board_path)

    source_run_root = Path(run_path).resolve(strict=False)
    _require_context_run_path(source_run_root, "run")
    if not source_run_root.exists() or not source_run_root.is_dir():
        raise ValueError(f"run path does not exist or is not a directory: {source_run_root}")
    registered_id = run_id or source_run_root.name
    _require_identifier(registered_id, "run id")

    run_manifest = _load_json_payload(source_run_root / "run.json", str(source_run_root / "run.json"))
    pipeline = _required_mapping(run_manifest, "pipeline", "run.json")
    status = _required_str(pipeline, "status", "run.json.pipeline.status")
    if status not in {"awaiting_approval", "ready_for_next_stage", "complete"}:
        raise ValueError(f"run.json.pipeline.status has unsupported value {status!r}")

    destination_root = board_root / "onboarding" / "runs" / registered_id
    if destination_root.exists():
        raise ValueError(f"onboarding run already exists: {registered_id}")

    if any(existing.id == registered_id for existing in board.onboarding_runs):
        raise ValueError(f"run id already registered: {registered_id}")

    if status == "complete":
        derived_run_lifecycle = "approved"
        region_count = _validate_and_count_regions(source_run_root, board)
    else:
        derived_run_lifecycle = "onboarding"
        region_count = _estimate_region_count(source_run_root)
    derived_board_lifecycle = _max_lifecycle(board.lifecycle, derived_run_lifecycle)

    destination_root.parent.mkdir(parents=True, exist_ok=True)
    _require_tree_without_symlinks(source_run_root)
    shutil.copytree(source_run_root, destination_root)

    updated_run = OnboardingRun(
        id=registered_id,
        path=Path("onboarding") / "runs" / registered_id,
        region_count=region_count,
        lifecycle=derived_run_lifecycle,
        status=status,
    )
    board = replace(
        board,
        lifecycle=derived_board_lifecycle,
        onboarding_runs=board.onboarding_runs + [updated_run],
    )
    board_path.write_text(
        json.dumps(board.to_json(), indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    updated_catalog = CatalogDocument(
        boards=[
            replace(entry, lifecycle=derived_board_lifecycle) if entry.id == board_id else entry
            for entry in catalog.boards
        ],
        schema_version=catalog.schema_version,
    )
    Path(catalog_path).write_text(
        json.dumps(updated_catalog.to_json(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return board


def render_swift_catalog(board: BoardDocument) -> str:
    override = _swift_board_override(board)
    manufacturer = _required_board_metadata(board.manufacturer, board.id, "manufacturer")
    name = _required_board_metadata(board.name, board.id, "name")
    dimensions = _required_board_metadata(board.dimensions, board.id, "dimensions")
    product_url = _required_board_metadata(board.product_url, board.id, "productURL")
    aspect_ratio = _required_board_number(board.aspect_ratio, board.id, "aspectRatio")
    subtitle = override["subtitle"] or f"{manufacturer} {name}"
    photo_asset_name = override["photoAssetName"]
    lines = [
        f"    static let {override['staticName']} = TrainingBoard(",
        f"        id: {_swift_string_literal(board.id)},",
        f"        manufacturer: {_swift_string_literal(manufacturer)},",
        f"        name: {_swift_string_literal(name)},",
        f"        subtitle: {_swift_string_literal(subtitle)},",
        f"        dimensions: {_swift_string_literal(dimensions)},",
        f"        aspectRatio: {_format_swift_number(aspect_ratio)},",
        "        holds: [",
    ]
    for hold in board.holds:
        lines.extend(_render_swift_hold(hold))
    lines.extend(
        [
            "        ],",
            f"        productURL: URL(string: {_swift_string_literal(product_url)})!,",
            (
                f"        photoAssetName: {_swift_string_literal(photo_asset_name)}"
                if photo_asset_name is not None
                else "        photoAssetName: nil"
            ),
            "    )",
        ]
    )
    return "\n".join(lines)


def export_swift_catalog(catalog_path: Path, output_path: Path, check: bool = False) -> None:
    catalog = validate_catalog(catalog_path)
    catalog_root = Path(catalog_path).parent.resolve(strict=False)
    boards = [
        load_board(catalog_root / entry.path)
        for entry in sorted(catalog.boards, key=lambda candidate: candidate.id)
    ]
    rendered = _render_swift_catalog_file(boards)
    destination = Path(output_path)
    current = destination.read_text(encoding="utf-8") if destination.exists() else None
    if check:
        if current != rendered:
            raise ValueError(
                f"Swift board catalog drift detected for {destination}; run scripts/export-board-catalog.sh"
            )
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    if current != rendered:
        destination.write_text(rendered, encoding="utf-8")


def _render_swift_catalog_file(boards: list[BoardDocument]) -> str:
    if not boards:
        raise ValueError("catalog must contain at least one board")
    declarations = [render_swift_catalog(board) for board in boards]
    static_names = [_swift_board_override(board)["staticName"] for board in boards]
    lines = [
        _SWIFT_HEADER.rstrip(),
        "",
        "enum GeneratedBoardCatalog {",
    ]
    for index, declaration in enumerate(declarations):
        lines.append(declaration)
        if index != len(declarations) - 1:
            lines.append("")
    lines.extend(
        [
            "",
            f"    static let all: [TrainingBoard] = [{', '.join(static_names)}]",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def _load_json_payload(path: Path, source: str) -> Mapping[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise ValueError(f"{source} does not exist: {path}") from error
    except json.JSONDecodeError as error:
        raise ValueError(f"{source} is not valid JSON") from error
    except OSError as error:
        raise ValueError(f"cannot read {source}: {path}") from error
    if not isinstance(payload, Mapping):
        raise ValueError(f"{source} must be a JSON object")
    return payload


def _required_str(payload: Mapping[str, Any], key: str, source: str) -> str:
    if key not in payload:
        raise ValueError(f"{source} is missing")
    value = payload[key]
    if not isinstance(value, str) or not value:
        raise ValueError(f"{source} must be a non-empty string")
    return value


def _required_mapping(payload: Mapping[str, Any], key: str, source: str) -> Mapping[str, Any]:
    if key not in payload:
        raise ValueError(f"{source}.{key} is missing")
    value = payload[key]
    if not isinstance(value, Mapping):
        raise ValueError(f"{source}.{key} must be an object")
    return value


def _required_list(payload: Mapping[str, Any], key: str, source: str) -> list[Any]:
    if key not in payload:
        raise ValueError(f"{source} is missing")
    value = payload[key]
    if not isinstance(value, list):
        raise ValueError(f"{source} must be an array")
    return value


def _required_int(payload: Mapping[str, Any], key: str, source: str) -> int:
    if key not in payload:
        raise ValueError(f"{source} is missing")
    value = payload[key]
    if not isinstance(value, int):
        raise ValueError(f"{source} must be an integer")
    return value


def _required_float(payload: Mapping[str, Any], key: str, source: str) -> float:
    if key not in payload:
        raise ValueError(f"{source} is missing")
    value = payload[key]
    if not isinstance(value, (float, int)):
        raise ValueError(f"{source} must be a number")
    return float(value)


def _require_identifier(value: str, description: str) -> None:
    if not _IDENTIFIER.fullmatch(value):
        raise ValueError(f"{description} must be a safe identifier: {value!r}")


def _require_relative_subpath(root: Path, candidate: Path, source: str) -> None:
    if candidate.is_absolute():
        raise ValueError(f"{source} must be a relative path: {candidate}")
    resolved = (root / candidate).resolve(strict=False)
    if not resolved.is_relative_to(root.resolve(strict=False)):
        raise ValueError(f"{source} must stay inside the containing directory: {candidate}")


def _find_board_entry(catalog: CatalogDocument, board_id: str) -> CatalogBoardEntry | None:
    for entry in catalog.boards:
        if entry.id == board_id:
            return entry
    return None


def _require_context_run_path(candidate: Path, source: str) -> None:
    resolved_candidate = candidate.resolve(strict=False)
    for parent in (resolved_candidate, *resolved_candidate.parents):
        if parent.name == ".context":
            return
    raise ValueError(f"{source} path must be inside a .context directory")


def _require_tree_without_symlinks(root: Path) -> None:
    if root.is_symlink():
        raise ValueError(f"run path must not contain symlinks: {root}")
    for candidate in root.rglob("*"):
        if candidate.is_symlink():
            raise ValueError(f"run path must not contain symlinks: {candidate}")


def _max_lifecycle(current: str, candidate: str) -> str:
    ordering = {name: index for index, name in enumerate(_LIFECYCLES)}
    return current if ordering[current] >= ordering[candidate] else candidate


def _swift_board_override(board: BoardDocument) -> Mapping[str, str | None]:
    override = _SWIFT_BOARD_OVERRIDES.get(board.id)
    if override is not None:
        return override
    return {
        "staticName": _swift_static_name(board.id),
        "subtitle": f"{board.manufacturer or board.id} {board.name or ''}".strip(),
        "photoAssetName": None,
    }


def _swift_static_name(board_id: str) -> str:
    slug = board_id.rsplit(".", maxsplit=1)[-1]
    words = [part for part in re.split(r"[^a-zA-Z0-9]+", slug) if part]
    if not words:
        raise ValueError(f"cannot derive Swift symbol from board id {board_id!r}")
    head, *tail = words
    return head.lower() + "".join(word[:1].upper() + word[1:] for word in tail)


def _required_board_metadata(value: str | None, board_id: str, field_name: str) -> str:
    if value is None or not value:
        raise ValueError(f"board {board_id!r} is missing required Swift field {field_name}")
    return value


def _required_board_number(value: float | None, board_id: str, field_name: str) -> float:
    if value is None:
        raise ValueError(f"board {board_id!r} is missing required Swift field {field_name}")
    return value


def _render_swift_hold(hold: BoardHold) -> list[str]:
    properties = [
        f"                id: {_swift_string_literal(hold.id)}",
        f"                name: {_swift_string_literal(hold.name)}",
        f"                shortLabel: {_swift_string_literal(hold.short_label)}",
        f"                detail: {_swift_string_literal(hold.detail)}",
        f"                kind: .{hold.kind}",
        (
            "                frame: HoldFrame("
            f"x: {_format_swift_number(hold.frame.x)}, "
            f"y: {_format_swift_number(hold.frame.y)}, "
            f"width: {_format_swift_number(hold.frame.width)}, "
            f"height: {_format_swift_number(hold.frame.height)})"
        ),
    ]
    if hold.size_mm is not None:
        properties.append(f"                sizeMillimeters: {hold.size_mm}")
    if hold.grip_type is not None:
        properties.append(f"                gripType: .{hold.grip_type}")
    if hold.features:
        features = ", ".join(f".{feature}" for feature in hold.features)
        properties.append(f"                features: [{features}]")
    lines = ["            BoardHold("]
    for property_index, property_line in enumerate(properties):
        suffix = "," if property_index != len(properties) - 1 else ""
        lines.append(f"{property_line}{suffix}")
    lines.append("            ),")
    return lines


def _format_swift_number(value: float) -> str:
    return format(value, ".3f").rstrip("0").rstrip(".")


def _swift_string_literal(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _estimate_region_count(run_root: Path) -> int:
    manifest_path = run_root / "stages" / "04" / "attempt-0001" / "stage-4-manifest.json"
    if not manifest_path.exists():
        return 0
    manifest = _load_json_payload(manifest_path, str(manifest_path))
    return len(_required_list(manifest, "regions", str(manifest_path)))


def canonicalize_region_key(value: str) -> str:
    match = re.fullmatch(r"(.*)-(\d+)-(.*)", value)
    if not match:
        return value
    prefix, digit, suffix = match.groups()
    if digit not in _FINGER_WORDS:
        return value
    return f"{prefix}-{_FINGER_WORDS[digit]}-{suffix}"


def _validate_and_count_regions(run_root: Path, board: BoardDocument) -> int:
    run_manifest = _load_json_payload(run_root / "run.json", str(run_root / "run.json"))
    stages = _required_list(run_manifest, "stages", str(run_root / "run.json"))
    stage4_records = [stage for stage in stages if isinstance(stage, Mapping) and stage.get("stage") == 4]
    if not stage4_records:
        raise ValueError("complete onboarding run is missing stage 4")
    stage4 = stage4_records[-1]
    artifact_root = _required_str(stage4, "artifactRoot", "run manifest stage 4 artifactRoot")
    if Path(artifact_root).is_absolute() or ".." in Path(artifact_root).parts:
        raise ValueError("run manifest stage 4 artifactRoot must be a safe relative path")
    manifest_path = run_root / artifact_root / "stage-4-manifest.json"
    stage4_manifest = _load_json_payload(manifest_path, str(manifest_path))
    regions = _required_list(stage4_manifest, "regions", str(manifest_path))

    hold_by_region = {hold.region_id: hold.id for hold in board.holds if hold.region_id is not None}
    if len(hold_by_region) != len(board.holds):
        raise ValueError("all holds must include regionId for approved onboarding run registration")

    seen_region_ids: set[int] = set()
    for index, region in enumerate(regions):
        if not isinstance(region, Mapping):
            raise ValueError(f"{manifest_path}.regions[{index}] must be an object")
        region_id = _required_int(region, "id", f"{manifest_path}.regions[{index}].id")
        if region_id in seen_region_ids:
            raise ValueError(f"duplicate stage-4 region id {region_id}")
        seen_region_ids.add(region_id)
        key = _required_str(region, "key", f"{manifest_path}.regions[{index}].key")
        hold_id = hold_by_region.get(region_id)
        if hold_id is None:
            raise ValueError(f"run region id {region_id} has no matching hold on board")
        if canonicalize_region_key(key) != hold_id:
            raise ValueError(
                f"run region id {region_id} maps to {key!r} which does not match board hold {hold_id!r}"
            )

    if len(seen_region_ids) != len(hold_by_region):
        raise ValueError("run region count does not match board hold count")
    return len(seen_region_ids)
