from pathlib import Path
import json,hashlib
E=Path('.context/placid-badger-cad-second-half/pr-readiness-repair-2026-10-02/evo')
def read(arm):
 p=E/('train-postboot-'+arm+'-landscape');rows=[json.loads(l) for f in p.glob('events-*.jsonl') for l in f.read_bytes().splitlines()];trans=json.loads((p/'transition-observations.json').read_text());token=trans[0]['actualMutation']['sceneLifecycleToken'];host=json.loads((p/'normal-host-frame-validation.json').read_text());env=json.loads((p/'launch-review-environment.json').read_text())
 cpu=[r for r in rows if r.get('sceneLifecycleToken')==token and r.get('boardRenderMembership')]
 inputs={json.dumps(r['resolvedSurfaceInputs'],sort_keys=True) for r in rows if r.get('sceneLifecycleToken')==token and 'resolvedSurfaceInputs' in r}
 values={k:sorted({json.dumps(r.get(k),sort_keys=True) for r in cpu if k in r}) for k in ['rootTransform','cameraTransform']}
 values['projection']=sorted({json.dumps({k:r['boardRenderMembership'].get(k) for k in ['orthographic','perspective','near','far','verticalFOVDegrees']},sort_keys=True) for r in cpu})
 ctors=[r for r in rows if r['event']=='board-scene-constructed'];makes=[r for r in rows if r['event']=='view-make'];eventOrder=[r['event']+(':workout' if r.get('sceneLifecycleToken')==token else ':predecessor') for r in rows if r['event'] in ['board-scene-constructed','view-make','detach-trial-before','detach-trial-after','view-disappear']]
 return dict(endpoints=host['normalOwnEndpoints'],inputs=sorted(inputs),values=values,environment=env,code=json.loads((p/'installed-binary-gate.json').read_text())['sha256'],constructorCount=len(ctors),makeCount=len(makes),eventOrder=eventOrder)
a,b=read('control'),read('unmount');ea=dict(a['environment']);eb=dict(b['environment']);ea.pop('HANGTEN_REVIEW_DIAGNOSTIC_RUN');eb.pop('HANGTEN_REVIEW_DIAGNOSTIC_RUN');eb.pop('HANGTEN_REVIEW_UNMOUNT_TRAIN_FOR_WORKOUT')
checks=dict(sameBinary=a['code']==b['code'],onlyActionAndRunIDEnvironmentDifference=ea==eb,sameNormalFrameEndpoints=a['endpoints']==b['endpoints'],sameResolvedWorkoutInputs=a['inputs']==b['inputs'],sameRootCameraTransformSets=a['values']==b['values'],sameConstructorAndMakeCounts=a['constructorCount']==b['constructorCount']==2 and a['makeCount']==b['makeCount']==2)
out=E/'train-postboot-arm-comparison.json';assert not out.exists();out.write_text(json.dumps(dict(checks=checks,control=a,unmount=b,eventOrderingEqual=a['eventOrder']==b['eventOrder'],limitations=['Entity/actual scene IDs naturally differ between fresh processes; compare role and recorded membership, not pointer equality across runs.','Frame endpoints and sampled path comparison do not assert identical animation timing.','Lifecycle event ordering retained; init completion is not loader entry or GPU creation.']),indent=2)+'\n');print(json.dumps(checks,indent=2));assert all(checks.values())
