from pathlib import Path
import json,hashlib
w=Path(__file__).resolve().parent;h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();source=w/'candidate/metolius-simulator-3d.FCStd';sha=h(source);assert sha=='b7223032abe4b5c00a8b16d8ddcafed8b836d806795f1d37bbffab80ce5560ef';compiler=h(Path('Tools/HangboardCAD/compile_board.py'));assert compiler=='f4c0d4c2a9c79c02d349be2f71a14962fde3c5c2fa13b24b0b34d425272fc50d'
reports={name:json.loads((w/(name+'.json')).read_text()) for name in ['compile','compile-check','reproduce']};ownership={name:json.loads((w/(name+'-ownership.json')).read_text()) for name in reports}
for name,r in reports.items():
 assert r['sourceSHA256']==sha and r['sourceUnchanged'] and r['tessellationDeflectionMM']==.28 and len(r['contacts'])==30 and len(r['nodes'])==31
 assert ownership[name]['exitCode']==0 and ownership[name]['compilerBytesUnchanged'] and ownership[name]['compilerSHA256']==compiler
a=w/'candidate/assets';b=w/'reproduce-assets';assert (a/'primary.usdz').read_bytes()==(b/'primary.usdz').read_bytes();assert (a/'primary.model.json').read_bytes()==(b/'primary.model.json').read_bytes();model=h(a/'primary.usdz');descriptor=h(a/'primary.model.json');assert all(r['modelSHA256']==model for r in reports.values());assert json.loads((a/'primary.model.json').read_text())['modelSHA256']==model
r={'status':'pass','humanAcceptance':False,'canonicalPromotionPerformed':False,'sourceSHA256':sha,'modelSHA256':model,'descriptorSHA256':descriptor,'modelBytes':(a/'primary.usdz').stat().st_size,'triangles':reports['compile']['triangles'],'twoNormalExportsByteIdentical':True,'checkMatchesExports':True,'compilerSHA256':compiler,'sourceUnchanged':True,'rawPlasticManifestAndNormalFlagsPreserved':True,'tessellationDeflectionMM':.28,'jobs':{name:{'report':str(w/(name+'.json')),'reportSHA256':h(w/(name+'.json')),'ownership':str(w/(name+'-ownership.json')),'elapsedSeconds':ownership[name]['elapsedSeconds']} for name in reports},'limits':['Actual-app visual/selection and human approval are separate pending gates.','Overall thickness is an explicit display estimate; no blanket G1 claim across every roof join.']};(w/'reproducibility.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(r,indent=2))
