// Generated by scripts/export-board-catalog.py from Hangboards/catalog.json.
// Do not edit by hand.

import Foundation
import SwiftUI

enum GeneratedBoardCatalog {
    static let compactII = TrainingBoard(
        id: "metolius.wood-grips-compact-ii",
        manufacturer: "Metolius",
        name: "Wood Grips Compact II",
        subtitle: "A compact FSC-certified wood board for everyday strength work.",
        dimensions: "24\" × 6.2\"",
        aspectRatio: 3.88,
        holds: [
            BoardHold(
                id: "jug-left",
                name: "Left outer jug",
                shortLabel: "J",
                detail: "Open-hand jug",
                kind: .jug,
                frame: HoldFrame(x: 0, y: 0, width: 0.165, height: 0.255)
            ),
            BoardHold(
                id: "sloper-flat-left",
                name: "Left 56 mm flat sloper",
                shortLabel: "56F",
                detail: "Flat open-hand sloper",
                kind: .sloper,
                frame: HoldFrame(x: 0.158, y: 0.035, width: 0.19, height: 0.128),
                sizeMillimeters: 56,
                gripType: .sloper,
                features: [.largeSlope]
            ),
            BoardHold(
                id: "sloper-round-center",
                name: "Center 56 mm round sloper",
                shortLabel: "56R",
                detail: "Round open-hand sloper",
                kind: .sloper,
                frame: HoldFrame(x: 0.352, y: 0.035, width: 0.296, height: 0.128),
                sizeMillimeters: 56,
                gripType: .sloper,
                features: [.roundSloper]
            ),
            BoardHold(
                id: "sloper-flat-right",
                name: "Right 56 mm flat sloper",
                shortLabel: "56F",
                detail: "Flat open-hand sloper",
                kind: .sloper,
                frame: HoldFrame(x: 0.652, y: 0.035, width: 0.19, height: 0.128),
                sizeMillimeters: 56,
                gripType: .sloper,
                features: [.largeSlope]
            ),
            BoardHold(
                id: "jug-right",
                name: "Right outer jug",
                shortLabel: "J",
                detail: "Open-hand jug",
                kind: .jug,
                frame: HoldFrame(x: 0.835, y: 0, width: 0.165, height: 0.255)
            ),
            BoardHold(
                id: "edge-29-left",
                name: "Left 29 mm edge",
                shortLabel: "29E",
                detail: "Large edge",
                kind: .edge,
                frame: HoldFrame(x: 0.021, y: 0.245, width: 0.165, height: 0.27),
                sizeMillimeters: 29,
                features: [.largeEdge]
            ),
            BoardHold(
                id: "pocket-29-three-left",
                name: "Left 29 mm three-finger pocket",
                shortLabel: "29·3",
                detail: "Three-finger pocket",
                kind: .pocket,
                frame: HoldFrame(x: 0.199, y: 0.365, width: 0.109, height: 0.148),
                sizeMillimeters: 29,
                gripType: .threeFingerPocket
            ),
            BoardHold(
                id: "pocket-29-two-left",
                name: "Left 29 mm two-finger pocket",
                shortLabel: "29·2",
                detail: "Two-finger pocket",
                kind: .pocket,
                frame: HoldFrame(x: 0.328, y: 0.37, width: 0.077, height: 0.147),
                sizeMillimeters: 29,
                gripType: .twoFingerPocket
            ),
            BoardHold(
                id: "pocket-29-four-center",
                name: "Center 29 mm four-finger pocket",
                shortLabel: "29·4",
                detail: "Four-finger pocket",
                kind: .pocket,
                frame: HoldFrame(x: 0.425, y: 0.365, width: 0.15, height: 0.148),
                sizeMillimeters: 29,
                gripType: .fourFingerPocket
            ),
            BoardHold(
                id: "pocket-29-two-right",
                name: "Right 29 mm two-finger pocket",
                shortLabel: "29·2",
                detail: "Two-finger pocket",
                kind: .pocket,
                frame: HoldFrame(x: 0.595, y: 0.37, width: 0.077, height: 0.147),
                sizeMillimeters: 29,
                gripType: .twoFingerPocket
            ),
            BoardHold(
                id: "pocket-29-three-right",
                name: "Right 29 mm three-finger pocket",
                shortLabel: "29·3",
                detail: "Three-finger pocket",
                kind: .pocket,
                frame: HoldFrame(x: 0.692, y: 0.365, width: 0.109, height: 0.148),
                sizeMillimeters: 29,
                gripType: .threeFingerPocket
            ),
            BoardHold(
                id: "edge-29-right",
                name: "Right 29 mm edge",
                shortLabel: "29E",
                detail: "Large edge",
                kind: .edge,
                frame: HoldFrame(x: 0.814, y: 0.245, width: 0.165, height: 0.27),
                sizeMillimeters: 29,
                features: [.largeEdge]
            ),
            BoardHold(
                id: "edge-19-left",
                name: "Left 19 mm edge",
                shortLabel: "19E",
                detail: "Small edge",
                kind: .edge,
                frame: HoldFrame(x: 0.035, y: 0.62, width: 0.16, height: 0.245),
                sizeMillimeters: 19,
                features: [.mediumEdge, .smallEdge]
            ),
            BoardHold(
                id: "pocket-19-three-left",
                name: "Left 19 mm three-finger pocket",
                shortLabel: "19·3",
                detail: "Three-finger pocket",
                kind: .pocket,
                frame: HoldFrame(x: 0.216, y: 0.733, width: 0.104, height: 0.14),
                sizeMillimeters: 19,
                gripType: .threeFingerPocket
            ),
            BoardHold(
                id: "pocket-19-three-right",
                name: "Right 19 mm three-finger pocket",
                shortLabel: "19·3",
                detail: "Three-finger pocket",
                kind: .pocket,
                frame: HoldFrame(x: 0.68, y: 0.733, width: 0.104, height: 0.14),
                sizeMillimeters: 19,
                gripType: .threeFingerPocket
            ),
            BoardHold(
                id: "pocket-19-two-left",
                name: "Left 19 mm two-finger pocket",
                shortLabel: "19·2",
                detail: "Two-finger pocket",
                kind: .pocket,
                frame: HoldFrame(x: 0.336, y: 0.733, width: 0.073, height: 0.14),
                sizeMillimeters: 19,
                gripType: .twoFingerPocket
            ),
            BoardHold(
                id: "pocket-19-two-right",
                name: "Right 19 mm two-finger pocket",
                shortLabel: "19·2",
                detail: "Two-finger pocket",
                kind: .pocket,
                frame: HoldFrame(x: 0.591, y: 0.733, width: 0.073, height: 0.14),
                sizeMillimeters: 19,
                gripType: .twoFingerPocket
            ),
            BoardHold(
                id: "pocket-19-four-center",
                name: "Center 19 mm four-finger pocket",
                shortLabel: "19·4",
                detail: "Four-finger pocket",
                kind: .pocket,
                frame: HoldFrame(x: 0.425, y: 0.733, width: 0.15, height: 0.14),
                sizeMillimeters: 19,
                gripType: .fourFingerPocket
            ),
            BoardHold(
                id: "edge-19-right",
                name: "Right 19 mm edge",
                shortLabel: "19E",
                detail: "Small edge",
                kind: .edge,
                frame: HoldFrame(x: 0.805, y: 0.62, width: 0.16, height: 0.245),
                sizeMillimeters: 19,
                features: [.mediumEdge, .smallEdge]
            ),
        ],
        productURL: URL(string: "https://www.metoliusclimbing.com/collections/training-boards/products/wood-grips-ii-training-boards")!,
        photoAssetName: "CompactBoardIllustration"
    )

    static let all: [TrainingBoard] = [compactII]
}
