from pathlib import Path
import json,hashlib
E=Path('.context/placid-badger-cad-second-half/pr-readiness-repair-2026-10-02/evo');p=E/'prestart-hand-control-landscape';raw=next(p.glob('events-*.jsonl')).read_bytes();rows=[json.loads(x) for x in raw.splitlines()];trans=json.loads((p/'transition-observations.json').read_text());work=trans[0]['actualMutation']['sceneLifecycleToken'];full=[r for r in rows if r.get('sceneLifecycleToken')==work and 'syncDeliveryCounters' in r];phases=[]
for t in trans:
 a=t['actualMutation'];following=next(r for r in full if r['sequence']>a['sequence'] and r['event']=='highlight-before');stable=[r for r in full if a['sequence']<=r['sequence']<following['sequence']];b=stable[-1]
 c=a['syncDeliveryCounters'];d=b['syncDeliveryCounters'];prior=next(r for r in reversed(full) if r['sequence']<a['sequence'] and r['event']=='highlight-before');pc=prior['syncDeliveryCounters']
 phases.append(dict(phaseIndex=t['phaseIndex'],mode=t['mode'],mutationSequence=a['sequence'],mutationEpoch=a['epoch'],mutationUptime=a['uptime'],beforeMutationSequence=prior['sequence'],materialMutationDeltas={m:c['sceneTotals'][m]-pc['sceneTotals'][m] for m in c['sceneTotals']},lastPreNextSemanticSnapshotSequence=b['sequence'],lastSnapshotEpoch=b['epoch'],observationSpanSeconds=b['epoch']-a['epoch'],samePhaseEndpointDeltas={m:d['sceneTotals'][m]-c['sceneTotals'][m] for m in c['sceneTotals']},lastMetricUptimes=d['latestUptime'],lastMetricAgeAtSnapshot={m:b['uptime']-u for m,u in d['latestUptime'].items()},nextSemanticBeforeSequence=following['sequence'],nextSemanticBeforeEpoch=following['epoch'],followingBeforeCounts=following['syncDeliveryCounters']['sceneTotals']))
summary=dict(traceSHA256=hashlib.sha256(raw).hexdigest(),workoutSceneToken=work,phaseSummaries=phases,counterCheckpoints=[dict(sequence=r['sequence'],event=r['event'],epoch=r['epoch'],uptime=r['uptime'],mode=r.get('cachedMode'),counts=r['syncDeliveryCounters']['sceneTotals'],latest=r['syncDeliveryCounters']['latestUptime'],depth=r['syncDeliveryCounters']['synchronousScopeDepth']) for r in full],limitations=['Same-phase endpoint deltas describe aggregate calls between exact sampled checkpoints, not continuous activity or displayed state.','Latest timestamps represent CPU assignments/calls including equal values, not GPU commits.','Late first after-mutation snapshot can itself be the last same-phase checkpoint; zero-span endpoint does not imply no later work. Following highlight-before counts are separately retained and include new in-flight request.'])
out=E/'prestart-hand-control-phase-summary.json';assert not out.exists();out.write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps(phases,indent=2))
