"""Generated, closed-schema descriptors for Hang Ten USDZ board models.

This module deliberately derives every spatial value from USDZ node vertices.
It has no inputs for authored bounds, face-plane axes, or contact rectangles.
"""

from __future__ import annotations

import hashlib
import math
import re
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from types import MappingProxyType
from typing import Literal, TypeAlias


Vector2: TypeAlias = tuple[float, float]
Vector3: TypeAlias = tuple[float, float, float]
NodeRole: TypeAlias = Literal["body", "contact", "attachment"]

_COORDINATE_FRAME = "hang-ten-board-v1"
_SCHEMA_VERSION = 1
_SCHEMA_VERSION_V2 = 2
_DESCRIPTOR_KEYS = frozenset(
    {"schemaVersion", "coordinateFrame", "modelSHA256", "modelBounds", "nodes", "contacts"}
)
_DESCRIPTOR_V2_KEYS = frozenset(
    {"schemaVersion", "coordinateFrame", "modelSHA256", "modelBounds", "nodes", "contactSlots"}
)
_SHA256 = re.compile(r"^[0-9a-f]{64}$")


@dataclass(frozen=True)
class NodeBinding:
    """A named model node with its one permitted semantic role."""

    node_id: str
    role: NodeRole | str
    contact_id: str | None = None


@dataclass(frozen=True)
class SlotNodeBinding:
    """A reusable model node bound to a generic contact slot."""

    node_id: str
    role: NodeRole | str
    contact_slot_id: str | None = None


@dataclass(frozen=True)
class ModelBounds:
    """Physical metre bounds, derived across every bound node vertex."""

    min: Vector3
    max: Vector3


@dataclass(frozen=True)
class FacePlaneAABB:
    """A contact's normalized +X/+Y rectangle in hang-ten-board-v1."""

    min: Vector2
    max: Vector2


@dataclass(frozen=True, init=False)
class ContactDescriptorV1:
    """Generated descriptor data for a logical contact that may have several nodes.

    ``outline`` is the contact's authored front-plane hold polygon, normalized to
    the model face, supplied by the CAD compiler; when present the app draws and
    hit-tests it in preference to the mesh region.
    """

    node_ids: tuple[str, ...]
    face_plane_aabb: FacePlaneAABB
    center: Vector2
    outline: tuple[Vector2, ...]

    def __init__(self, *_args: object, **_kwargs: object) -> None:
        raise TypeError("ContactDescriptorV1 is generated by descriptor factories")

    @classmethod
    def _from_validated(
        cls,
        node_ids: tuple[str, ...],
        face_plane_aabb: FacePlaneAABB,
        center: Vector2,
        outline: tuple[Vector2, ...] = (),
    ) -> ContactDescriptorV1:
        descriptor = object.__new__(cls)
        object.__setattr__(descriptor, "node_ids", node_ids)
        object.__setattr__(descriptor, "face_plane_aabb", face_plane_aabb)
        object.__setattr__(descriptor, "center", center)
        object.__setattr__(descriptor, "outline", outline)
        return descriptor


@dataclass(frozen=True, init=False)
class ModelDescriptorV1:
    """Closed v1 model descriptor; construct it through ``compile_descriptor``."""

    model_sha256: str
    model_bounds: ModelBounds
    nodes: tuple[NodeBinding, ...]
    contacts: Mapping[str, ContactDescriptorV1]

    def __init__(self, *_args: object, **_kwargs: object) -> None:
        raise TypeError("ModelDescriptorV1 is generated by descriptor factories")

    @classmethod
    def _from_validated(
        cls,
        model_sha256: str,
        model_bounds: ModelBounds,
        nodes: tuple[NodeBinding, ...],
        contacts: Mapping[str, ContactDescriptorV1],
    ) -> ModelDescriptorV1:
        descriptor = object.__new__(cls)
        object.__setattr__(descriptor, "model_sha256", model_sha256)
        object.__setattr__(descriptor, "model_bounds", model_bounds)
        object.__setattr__(descriptor, "nodes", nodes)
        object.__setattr__(descriptor, "contacts", MappingProxyType(dict(contacts)))
        return descriptor

    def to_json(self) -> dict[str, object]:
        """Return the canonical deterministic JSON-ready representation."""
        return {
            "schemaVersion": _SCHEMA_VERSION,
            "coordinateFrame": _COORDINATE_FRAME,
            "modelSHA256": self.model_sha256,
            "modelBounds": _bounds_to_json(self.model_bounds),
            "nodes": [
                _node_to_json(node)
                for node in sorted(self.nodes, key=lambda node: node.node_id)
            ],
            "contacts": {
                contact_id: _contact_to_json(self.contacts[contact_id])
                for contact_id in sorted(self.contacts)
            },
        }

    @classmethod
    def from_json(cls, value: Mapping[str, object]) -> ModelDescriptorV1:
        """Load a closed, canonical generated descriptor representation.

        This validates the descriptor's internal derivation invariants.  Raw
        model geometry remains the sole source for a newly compiled descriptor.
        """
        if not isinstance(value, Mapping):
            raise ValueError("descriptor must be an object")
        _require_exact_keys(value, _DESCRIPTOR_KEYS, "descriptor")
        if value["schemaVersion"] != _SCHEMA_VERSION or isinstance(value["schemaVersion"], bool):
            raise ValueError("schemaVersion must be 1")
        if value["coordinateFrame"] != _COORDINATE_FRAME:
            raise ValueError("coordinateFrame must be hang-ten-board-v1")
        model_sha256 = _sha256(value["modelSHA256"])
        model_bounds = _parse_model_bounds(value["modelBounds"])
        _require_nonzero_face_span(model_bounds)
        nodes = _parse_nodes(value["nodes"])
        contacts = _parse_contacts(value["contacts"], nodes)
        return cls._from_validated(model_sha256, model_bounds, nodes, contacts)


@dataclass(frozen=True, init=False)
class ContactSlotDescriptorV2:
    """Generated descriptor data for a reusable logical contact slot.

    ``outline`` is the slot's authored front-plane hold polygon, normalized to
    the model face. It is supplied by the CAD compiler (the source document owns
    the hold geometry) and is the sole region the app draws and hit-tests; when
    absent the app falls back to ``face_plane_aabb``.
    """

    node_ids: tuple[str, ...]
    face_plane_aabb: FacePlaneAABB
    center: Vector2
    outline: tuple[Vector2, ...]

    def __init__(self, *_args: object, **_kwargs: object) -> None:
        raise TypeError("ContactSlotDescriptorV2 is generated by descriptor factories")

    @classmethod
    def _from_validated(
        cls,
        node_ids: tuple[str, ...],
        face_plane_aabb: FacePlaneAABB,
        center: Vector2,
        outline: tuple[Vector2, ...] = (),
    ) -> ContactSlotDescriptorV2:
        descriptor = object.__new__(cls)
        object.__setattr__(descriptor, "node_ids", node_ids)
        object.__setattr__(descriptor, "face_plane_aabb", face_plane_aabb)
        object.__setattr__(descriptor, "center", center)
        object.__setattr__(descriptor, "outline", outline)
        return descriptor


@dataclass(frozen=True, init=False)
class ModelDescriptorV2:
    """Closed v2 reusable model descriptor; use ``compile_reusable_descriptor``."""

    model_sha256: str
    model_bounds: ModelBounds
    nodes: tuple[SlotNodeBinding, ...]
    contact_slots: Mapping[str, ContactSlotDescriptorV2]

    def __init__(self, *_args: object, **_kwargs: object) -> None:
        raise TypeError("ModelDescriptorV2 is generated by descriptor factories")

    @classmethod
    def _from_validated(
        cls,
        model_sha256: str,
        model_bounds: ModelBounds,
        nodes: tuple[SlotNodeBinding, ...],
        contact_slots: Mapping[str, ContactSlotDescriptorV2],
    ) -> ModelDescriptorV2:
        descriptor = object.__new__(cls)
        object.__setattr__(descriptor, "model_sha256", model_sha256)
        object.__setattr__(descriptor, "model_bounds", model_bounds)
        object.__setattr__(descriptor, "nodes", nodes)
        object.__setattr__(descriptor, "contact_slots", MappingProxyType(dict(contact_slots)))
        return descriptor

    def to_json(self) -> dict[str, object]:
        return {
            "schemaVersion": _SCHEMA_VERSION_V2,
            "coordinateFrame": _COORDINATE_FRAME,
            "modelSHA256": self.model_sha256,
            "modelBounds": _bounds_to_json(self.model_bounds),
            "nodes": [_slot_node_to_json(node) for node in self.nodes],
            "contactSlots": {
                slot_id: _contact_slot_to_json(self.contact_slots[slot_id])
                for slot_id in sorted(self.contact_slots)
            },
        }

    @classmethod
    def from_json(cls, value: Mapping[str, object]) -> ModelDescriptorV2:
        if not isinstance(value, Mapping):
            raise ValueError("descriptor must be an object")
        _require_exact_keys(value, _DESCRIPTOR_V2_KEYS, "descriptor")
        if value["schemaVersion"] != _SCHEMA_VERSION_V2 or isinstance(value["schemaVersion"], bool):
            raise ValueError("schemaVersion must be 2")
        if value["coordinateFrame"] != _COORDINATE_FRAME:
            raise ValueError("coordinateFrame must be hang-ten-board-v1")
        model_sha256 = _sha256(value["modelSHA256"])
        model_bounds = _parse_model_bounds(value["modelBounds"])
        _require_nonzero_face_span(model_bounds)
        nodes = _parse_slot_nodes(value["nodes"])
        contact_slots = _parse_contact_slots(value["contactSlots"], nodes)
        return cls._from_validated(model_sha256, model_bounds, nodes, contact_slots)


def compile_reusable_descriptor(
    model_bytes: bytes,
    nodes: Sequence[SlotNodeBinding],
    vertices_by_node_id: Mapping[str, Sequence[Vector3]],
    contact_slot_ids: frozenset[str],
    outlines_by_slot: Mapping[str, Sequence[Vector2]] | None = None,
) -> ModelDescriptorV2:
    """Derive a deterministic reusable descriptor from bound node vertices.

    ``outlines_by_slot`` carries each slot's authored front-plane hold polygon
    (native XZ, in the same space as the node vertices' X/Y). The source CAD
    document owns hold geometry, so when an outline is present it — not the
    exported mesh silhouette — defines the slot's region, ``facePlaneAABB`` and
    ``center``. Slots without an outline fall back to the mesh-derived region.
    """
    if not isinstance(model_bytes, bytes):
        raise ValueError("model_bytes must be exact USDZ bytes")
    bindings = _validate_slot_bindings(nodes)
    slots = _validate_logical_contact_ids(contact_slot_ids)
    vertices = _validate_slot_bound_geometry(bindings, vertices_by_node_id)
    actual_slots = {binding.contact_slot_id for binding in bindings if binding.role == "contact"}
    if actual_slots != slots:
        raise ValueError("bound contact slot IDs must equal logical contact slot IDs")
    raw_bounds = _raw_model_bounds(vertices.values())
    _require_nonzero_face_span(raw_bounds)
    return ModelDescriptorV2._from_validated(
        hashlib.sha256(model_bytes).hexdigest(),
        _rounded_bounds(raw_bounds),
        tuple(sorted(bindings, key=lambda item: item.node_id)),
        _compile_contact_slots(bindings, vertices, raw_bounds, slots, outlines_by_slot or {}),
    )


def compile_descriptor(
    model_bytes: bytes,
    nodes: Sequence[NodeBinding],
    vertices_by_node_id: Mapping[str, Sequence[Vector3]],
    logical_contact_ids: frozenset[str],
    outlines_by_contact: Mapping[str, Sequence[Vector2]] | None = None,
) -> ModelDescriptorV1:
    """Derive a deterministic descriptor solely from bound USDZ node vertices.

    ``outlines_by_contact`` carries each contact's authored front-plane hold
    polygon (native XZ, in the same space as the node vertices' X/Y); when
    present the CAD-authored region, not the exported mesh silhouette, defines
    the contact's ``outline``, ``facePlaneAABB`` and ``center``.
    """
    if not isinstance(model_bytes, bytes):
        raise ValueError("model_bytes must be exact USDZ bytes")
    bindings = _validate_bindings(nodes)
    expected_contact_ids = _validate_logical_contact_ids(logical_contact_ids)
    vertices = _validate_bound_geometry(bindings, vertices_by_node_id)
    actual_contact_ids = {binding.contact_id for binding in bindings if binding.role == "contact"}
    if actual_contact_ids != expected_contact_ids:
        raise ValueError("bound contact IDs must equal logical contact IDs")

    raw_model_bounds = _raw_model_bounds(vertices.values())
    _require_nonzero_face_span(raw_model_bounds)
    contacts = _compile_contacts(bindings, vertices, raw_model_bounds, outlines_by_contact or {})
    return ModelDescriptorV1._from_validated(
        hashlib.sha256(model_bytes).hexdigest(),
        _rounded_bounds(raw_model_bounds),
        tuple(sorted(bindings, key=lambda binding: binding.node_id)),
        contacts,
    )


def _validate_slot_bindings(nodes: Sequence[SlotNodeBinding]) -> list[SlotNodeBinding]:
    if isinstance(nodes, (str, bytes)) or not isinstance(nodes, Sequence):
        raise ValueError("nodes must be a sequence of SlotNodeBinding values")
    bindings = list(nodes)
    node_ids: set[str] = set()
    body_count = 0
    for binding in bindings:
        if not isinstance(binding, SlotNodeBinding):
            raise ValueError("nodes must contain SlotNodeBinding values")
        if not isinstance(binding.node_id, str) or not binding.node_id:
            raise ValueError("nodeID must be a non-empty string")
        if binding.node_id in node_ids:
            raise ValueError(f"duplicate nodeID: {binding.node_id}")
        node_ids.add(binding.node_id)
        if binding.role not in {"body", "contact", "attachment"}:
            raise ValueError(f"unknown node role: {binding.role}")
        if binding.role == "body":
            body_count += 1
            if binding.contact_slot_id is not None:
                raise ValueError("body node may not declare contactSlotID")
        elif binding.role == "attachment":
            if binding.contact_slot_id is not None:
                raise ValueError("attachment node may not declare contactSlotID")
        elif not isinstance(binding.contact_slot_id, str) or not binding.contact_slot_id:
            raise ValueError("contact node requires a non-empty contactSlotID")
    if body_count == 0:
        raise ValueError("descriptor requires a body node")
    return bindings


def _validate_slot_bound_geometry(
    bindings: Sequence[SlotNodeBinding], vertices_by_node_id: Mapping[str, Sequence[Vector3]]
) -> dict[str, tuple[Vector3, ...]]:
    return _validate_bound_geometry(
        [NodeBinding(binding.node_id, binding.role, binding.contact_slot_id) for binding in bindings],
        vertices_by_node_id,
    )


def _compile_contact_slots(
    bindings: Sequence[SlotNodeBinding],
    vertices_by_node_id: Mapping[str, Sequence[Vector3]],
    model_bounds: ModelBounds,
    slots: set[str],
    outlines_by_slot: Mapping[str, Sequence[Vector2]],
) -> dict[str, ContactSlotDescriptorV2]:
    converted = [NodeBinding(binding.node_id, binding.role, binding.contact_slot_id) for binding in bindings]
    contacts = _compile_contacts(converted, vertices_by_node_id, model_bounds, outlines_by_slot)
    return {
        slot_id: ContactSlotDescriptorV2._from_validated(
            contacts[slot_id].node_ids,
            contacts[slot_id].face_plane_aabb,
            contacts[slot_id].center,
            contacts[slot_id].outline,
        )
        for slot_id in sorted(slots)
    }


def _validate_bindings(nodes: Sequence[NodeBinding]) -> list[NodeBinding]:
    if isinstance(nodes, (str, bytes)) or not isinstance(nodes, Sequence):
        raise ValueError("nodes must be a sequence of NodeBinding values")
    bindings = list(nodes)
    node_ids: set[str] = set()
    body_count = 0
    for binding in bindings:
        if not isinstance(binding, NodeBinding):
            raise ValueError("nodes must contain NodeBinding values")
        if not isinstance(binding.node_id, str) or not binding.node_id:
            raise ValueError("nodeID must be a non-empty string")
        if binding.node_id in node_ids:
            raise ValueError(f"duplicate nodeID: {binding.node_id}")
        node_ids.add(binding.node_id)
        if binding.role == "decoration":
            raise ValueError("decoration nodes are not permitted")
        if binding.role not in {"body", "contact", "attachment"}:
            raise ValueError(f"unknown node role: {binding.role}")
        if binding.role == "body":
            body_count += 1
            if binding.contact_id is not None:
                raise ValueError("body node may not declare contactID")
        elif binding.role == "attachment":
            if binding.contact_id is not None:
                raise ValueError("attachment node may not declare contactID")
        elif not isinstance(binding.contact_id, str) or not binding.contact_id:
            raise ValueError("contact node requires a non-empty contactID")
    if body_count == 0:
        raise ValueError("descriptor requires a body node")
    return bindings


def _validate_logical_contact_ids(logical_contact_ids: frozenset[str]) -> set[str]:
    if not isinstance(logical_contact_ids, frozenset):
        raise ValueError("logical contact IDs must be a frozenset")
    if any(not isinstance(contact_id, str) or not contact_id for contact_id in logical_contact_ids):
        raise ValueError("logical contact IDs must contain non-empty strings")
    return set(logical_contact_ids)


def _validate_bound_geometry(
    bindings: Sequence[NodeBinding], vertices_by_node_id: Mapping[str, Sequence[Vector3]]
) -> dict[str, tuple[Vector3, ...]]:
    if not isinstance(vertices_by_node_id, Mapping):
        raise ValueError("vertices_by_node_id must be a mapping")
    bound_ids = {binding.node_id for binding in bindings}
    geometry_ids = set(vertices_by_node_id)
    unbound_ids = geometry_ids - bound_ids
    if unbound_ids:
        raise ValueError(f"unbound geometry for nodeID: {sorted(unbound_ids)[0]}")
    missing_ids = bound_ids - geometry_ids
    if missing_ids:
        raise ValueError(f"node/vertex disagreement for nodeID: {sorted(missing_ids)[0]}")
    parsed: dict[str, tuple[Vector3, ...]] = {}
    for node_id in bound_ids:
        raw_vertices = vertices_by_node_id[node_id]
        if isinstance(raw_vertices, (str, bytes)) or not isinstance(raw_vertices, Sequence):
            raise ValueError(f"vertices for nodeID must be a sequence: {node_id}")
        if not raw_vertices:
            raise ValueError(f"nodeID has zero vertices: {node_id}")
        parsed[node_id] = tuple(_vector3(vertex, f"vertex for nodeID {node_id}") for vertex in raw_vertices)
    return parsed


def _vector3(value: object, field: str) -> Vector3:
    if isinstance(value, (str, bytes)) or not isinstance(value, Sequence) or len(value) != 3:
        raise ValueError(f"{field} must contain exactly three coordinates")
    coordinates = tuple(_finite_number(coordinate, field) for coordinate in value)
    return (coordinates[0], coordinates[1], coordinates[2])


def _finite_number(value: object, field: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value):
        raise ValueError(f"{field} coordinates must be finite numbers")
    return float(value)


def _raw_model_bounds(vertices_by_node: Iterable[Sequence[Vector3]]) -> ModelBounds:
    vertices = [
        vertex for node_vertices in vertices_by_node for vertex in node_vertices
    ]
    return ModelBounds(
        min=(
            min(vertex[0] for vertex in vertices),
            min(vertex[1] for vertex in vertices),
            min(vertex[2] for vertex in vertices),
        ),
        max=(
            max(vertex[0] for vertex in vertices),
            max(vertex[1] for vertex in vertices),
            max(vertex[2] for vertex in vertices),
        ),
    )


def _rounded_bounds(bounds: ModelBounds) -> ModelBounds:
    return ModelBounds(
        min=tuple(_round(value) for value in bounds.min),
        max=tuple(_round(value) for value in bounds.max),
    )


def _require_nonzero_face_span(model_bounds: ModelBounds) -> None:
    for axis in range(2):
        span = model_bounds.max[axis] - model_bounds.min[axis]
        if not math.isfinite(span):
            raise ValueError("derived model face span must be finite")
        if span <= 0:
            raise ValueError("model bounds must have non-zero face span in +X and +Y")


def _outline_region(
    raw_outline: Sequence[Vector2], model_bounds: ModelBounds
) -> tuple[tuple[Vector2, ...], FacePlaneAABB, Vector2]:
    """Normalize an authored outline and derive its AABB and center from it."""

    def clamp(value: float) -> float:
        # The authored outline lies on the model face; float rounding at the
        # envelope can push a normalized edge a few ulps outside [0, 1].
        return 0.0 if value < 0.0 else (1.0 if value > 1.0 else value)

    outline = tuple(
        (
            clamp(_normalize(_finite_number(point[0], "outline"), model_bounds.min[0], model_bounds.max[0])),
            clamp(_normalize(_finite_number(point[1], "outline"), model_bounds.min[1], model_bounds.max[1])),
        )
        for point in raw_outline
    )
    if len(outline) < 3:
        raise ValueError("outline needs at least three points")
    min_x = min(point[0] for point in outline)
    max_x = max(point[0] for point in outline)
    min_y = min(point[1] for point in outline)
    max_y = max(point[1] for point in outline)
    return (
        outline,
        FacePlaneAABB(min=(min_x, min_y), max=(max_x, max_y)),
        (_midpoint(min_x, max_x), _midpoint(min_y, max_y)),
    )


def _compile_contacts(
    bindings: Sequence[NodeBinding],
    vertices_by_node_id: Mapping[str, Sequence[Vector3]],
    model_bounds: ModelBounds,
    outlines_by_contact: Mapping[str, Sequence[Vector2]] | None = None,
) -> dict[str, ContactDescriptorV1]:
    outlines = outlines_by_contact or {}
    node_ids_by_contact: dict[str, list[str]] = {}
    vertices_by_contact: dict[str, list[Vector3]] = {}
    for binding in bindings:
        if binding.role == "contact":
            assert binding.contact_id is not None
            node_ids_by_contact.setdefault(binding.contact_id, []).append(binding.node_id)
            vertices_by_contact.setdefault(binding.contact_id, []).extend(vertices_by_node_id[binding.node_id])
    result: dict[str, ContactDescriptorV1] = {}
    for contact_id in sorted(node_ids_by_contact):
        raw_outline = outlines.get(contact_id)
        if raw_outline:
            outline, face_bounds, center = _outline_region(raw_outline, model_bounds)
        else:
            outline = ()
            contact_vertices = vertices_by_contact[contact_id]
            min_x, max_x = min(vertex[0] for vertex in contact_vertices), max(vertex[0] for vertex in contact_vertices)
            min_y, max_y = min(vertex[1] for vertex in contact_vertices), max(vertex[1] for vertex in contact_vertices)
            face_bounds = FacePlaneAABB(
                min=(
                    _normalize(min_x, model_bounds.min[0], model_bounds.max[0]),
                    _normalize(min_y, model_bounds.min[1], model_bounds.max[1]),
                ),
                max=(
                    _normalize(max_x, model_bounds.min[0], model_bounds.max[0]),
                    _normalize(max_y, model_bounds.min[1], model_bounds.max[1]),
                ),
            )
            center = (
                _midpoint(face_bounds.min[0], face_bounds.max[0]),
                _midpoint(face_bounds.min[1], face_bounds.max[1]),
            )
        result[contact_id] = ContactDescriptorV1._from_validated(
            tuple(sorted(node_ids_by_contact[contact_id])),
            face_bounds,
            center,
            outline,
        )
    return result


def _normalize(value: float, minimum: float, maximum: float) -> float:
    offset = value - minimum
    span = maximum - minimum
    if not math.isfinite(offset) or not math.isfinite(span):
        raise ValueError("derived normalized coordinates must be finite")
    normalized = offset / span
    if not math.isfinite(normalized):
        raise ValueError("derived normalized coordinates must be finite")
    return _round(normalized)


def _midpoint(minimum: float, maximum: float) -> float:
    span = maximum - minimum
    if not math.isfinite(span):
        raise ValueError("derived center coordinates must be finite")
    midpoint = minimum + span / 2
    if not math.isfinite(midpoint):
        raise ValueError("derived center coordinates must be finite")
    return _round(midpoint)


def _round(value: float) -> float:
    if not math.isfinite(value):
        raise ValueError("derived descriptor numbers must be finite")
    rounded = round(value, 9)
    if not math.isfinite(rounded):
        raise ValueError("derived descriptor numbers must be finite")
    return rounded


def _bounds_to_json(bounds: ModelBounds) -> dict[str, object]:
    return {"min": list(bounds.min), "max": list(bounds.max)}


def _node_to_json(node: NodeBinding) -> dict[str, str]:
    value: dict[str, str] = {"nodeID": node.node_id, "role": node.role}
    if node.role == "contact":
        assert node.contact_id is not None
        value["contactID"] = node.contact_id
    return value


def _slot_node_to_json(node: SlotNodeBinding) -> dict[str, str]:
    value: dict[str, str] = {"nodeID": node.node_id, "role": node.role}
    if node.role == "contact":
        assert node.contact_slot_id is not None
        value["contactSlotID"] = node.contact_slot_id
    return value


def _contact_to_json(contact: ContactDescriptorV1) -> dict[str, object]:
    value: dict[str, object] = {
        "nodeIDs": list(contact.node_ids),
        "facePlaneAABB": {"min": list(contact.face_plane_aabb.min), "max": list(contact.face_plane_aabb.max)},
        "center": list(contact.center),
    }
    if contact.outline:
        value["outline"] = [list(point) for point in contact.outline]
    return value


def _contact_slot_to_json(contact: ContactSlotDescriptorV2) -> dict[str, object]:
    value: dict[str, object] = {
        "nodeIDs": list(contact.node_ids),
        "facePlaneAABB": {"min": list(contact.face_plane_aabb.min), "max": list(contact.face_plane_aabb.max)},
        "center": list(contact.center),
    }
    if contact.outline:
        value["outline"] = [list(point) for point in contact.outline]
    return value


def _require_exact_keys(
    value: Mapping[str, object], expected: frozenset[str], field: str,
    optional: frozenset[str] = frozenset(),
) -> None:
    unknown = set(value) - expected - optional
    if unknown:
        raise ValueError(f"{field} contains unknown key: {sorted(unknown)[0]}")
    missing = expected - set(value)
    if missing:
        raise ValueError(f"{field} is missing key: {sorted(missing)[0]}")


def _sha256(value: object) -> str:
    if not isinstance(value, str) or not _SHA256.fullmatch(value):
        raise ValueError("modelSHA256 must be a lowercase SHA-256 digest")
    return value


def _parse_model_bounds(value: object) -> ModelBounds:
    mapping = _mapping(value, "modelBounds")
    _require_exact_keys(mapping, frozenset({"min", "max"}), "modelBounds")
    bounds = ModelBounds(
        min=_vector3_json(mapping["min"], "modelBounds.min"),
        max=_vector3_json(mapping["max"], "modelBounds.max"),
    )
    if any(bounds.min[axis] > bounds.max[axis] for axis in range(3)):
        raise ValueError("modelBounds minimum may not exceed maximum")
    return bounds


def _parse_nodes(value: object) -> tuple[NodeBinding, ...]:
    raw_nodes = _sequence(value, "nodes")
    nodes: list[NodeBinding] = []
    for raw_node in raw_nodes:
        mapping = _mapping(raw_node, "node")
        role = mapping.get("role")
        expected = frozenset({"nodeID", "role", "contactID"}) if role == "contact" else frozenset({"nodeID", "role"})
        _require_exact_keys(mapping, expected, "node")
        node_id = mapping["nodeID"]
        if not isinstance(node_id, str) or not node_id:
            raise ValueError("nodeID must be a non-empty string")
        if role not in {"body", "contact", "attachment"}:
            raise ValueError("node role must be body, contact, or attachment")
        contact_id = mapping.get("contactID")
        if role == "contact" and (not isinstance(contact_id, str) or not contact_id):
            raise ValueError("contact node requires a non-empty contactID")
        nodes.append(NodeBinding(node_id, role, contact_id if role == "contact" else None))
    _validate_bindings(nodes)
    if [node.node_id for node in nodes] != sorted(node.node_id for node in nodes):
        raise ValueError("nodes must be sorted by nodeID")
    return tuple(nodes)


def _parse_contacts(value: object, nodes: Sequence[NodeBinding]) -> dict[str, ContactDescriptorV1]:
    contacts = _mapping(value, "contacts")
    if list(contacts) != sorted(contacts):
        raise ValueError("contacts must be sorted by contactID")
    expected_by_contact: dict[str, list[str]] = {}
    for node in nodes:
        if node.role == "contact":
            assert node.contact_id is not None
            expected_by_contact.setdefault(node.contact_id, []).append(node.node_id)
    if set(contacts) != set(expected_by_contact):
        raise ValueError("contacts must equal node contact IDs")
    parsed: dict[str, ContactDescriptorV1] = {}
    for contact_id, raw_contact in contacts.items():
        if not isinstance(contact_id, str) or not contact_id:
            raise ValueError("contact IDs must be non-empty strings")
        mapping = _mapping(raw_contact, f"contact {contact_id}")
        _require_exact_keys(
            mapping,
            frozenset({"nodeIDs", "facePlaneAABB", "center"}),
            f"contact {contact_id}",
            frozenset({"outline"}),
        )
        node_ids = _string_sequence(mapping["nodeIDs"], f"contact {contact_id}.nodeIDs")
        if not node_ids or node_ids != sorted(node_ids) or node_ids != sorted(expected_by_contact[contact_id]):
            raise ValueError(f"contact {contact_id} nodeIDs must exactly match bound nodes")
        bounds_mapping = _mapping(mapping["facePlaneAABB"], f"contact {contact_id}.facePlaneAABB")
        _require_exact_keys(bounds_mapping, frozenset({"min", "max"}), f"contact {contact_id}.facePlaneAABB")
        face_bounds = FacePlaneAABB(
            min=_vector2_json(bounds_mapping["min"], f"contact {contact_id}.facePlaneAABB.min"),
            max=_vector2_json(bounds_mapping["max"], f"contact {contact_id}.facePlaneAABB.max"),
        )
        if any(face_bounds.min[axis] > face_bounds.max[axis] for axis in range(2)) or any(
            coordinate < 0 or coordinate > 1 for coordinate in (*face_bounds.min, *face_bounds.max)
        ):
            raise ValueError(f"contact {contact_id} facePlaneAABB must be normalized")
        center = _vector2_json(mapping["center"], f"contact {contact_id}.center")
        expected_center = (
            _midpoint(face_bounds.min[0], face_bounds.max[0]),
            _midpoint(face_bounds.min[1], face_bounds.max[1]),
        )
        if center != expected_center:
            raise ValueError(f"contact {contact_id} center must derive from facePlaneAABB")
        outline: tuple[Vector2, ...] = ()
        if "outline" in mapping:
            outline = tuple(
                _vector2_json(point, f"contact {contact_id}.outline")
                for point in _sequence(mapping["outline"], f"contact {contact_id}.outline")
            )
            if len(outline) < 3:
                raise ValueError(f"contact {contact_id} outline needs at least three points")
            if any(coordinate < 0 or coordinate > 1 for point in outline for coordinate in point):
                raise ValueError(f"contact {contact_id} outline must be normalized")
            expected_bounds = FacePlaneAABB(
                min=(min(p[0] for p in outline), min(p[1] for p in outline)),
                max=(max(p[0] for p in outline), max(p[1] for p in outline)),
            )
            if face_bounds != expected_bounds:
                raise ValueError(f"contact {contact_id} facePlaneAABB must derive from its outline")
            if center != (
                _midpoint(expected_bounds.min[0], expected_bounds.max[0]),
                _midpoint(expected_bounds.min[1], expected_bounds.max[1]),
            ):
                raise ValueError(f"contact {contact_id} center must derive from its outline")
        parsed[contact_id] = ContactDescriptorV1._from_validated(
            tuple(node_ids), face_bounds, center, outline
        )
    return parsed


def _parse_slot_nodes(value: object) -> tuple[SlotNodeBinding, ...]:
    raw_nodes = _sequence(value, "nodes")
    nodes: list[SlotNodeBinding] = []
    for raw_node in raw_nodes:
        mapping = _mapping(raw_node, "node")
        role = mapping.get("role")
        expected = frozenset({"nodeID", "role", "contactSlotID"}) if role == "contact" else frozenset({"nodeID", "role"})
        _require_exact_keys(mapping, expected, "node")
        node_id = mapping["nodeID"]
        if not isinstance(node_id, str) or not node_id:
            raise ValueError("nodeID must be a non-empty string")
        if role not in {"body", "contact", "attachment"}:
            raise ValueError("node role must be body, contact, or attachment")
        slot_id = mapping.get("contactSlotID")
        if role == "contact" and (not isinstance(slot_id, str) or not slot_id):
            raise ValueError("contact node requires a non-empty contactSlotID")
        nodes.append(SlotNodeBinding(node_id, role, slot_id if role == "contact" else None))
    _validate_slot_bindings(nodes)
    if [node.node_id for node in nodes] != sorted(node.node_id for node in nodes):
        raise ValueError("nodes must be sorted by nodeID")
    return tuple(nodes)


def _parse_contact_slots(value: object, nodes: Sequence[SlotNodeBinding]) -> dict[str, ContactSlotDescriptorV2]:
    slots = _mapping(value, "contactSlots")
    if list(slots) != sorted(slots):
        raise ValueError("contactSlots must be sorted by contactSlotID")
    expected_by_slot: dict[str, list[str]] = {}
    for node in nodes:
        if node.role == "contact":
            assert node.contact_slot_id is not None
            expected_by_slot.setdefault(node.contact_slot_id, []).append(node.node_id)
    if set(slots) != set(expected_by_slot):
        raise ValueError("contactSlots must equal node contact slot IDs")
    parsed: dict[str, ContactSlotDescriptorV2] = {}
    for slot_id, raw_slot in slots.items():
        if not isinstance(slot_id, str) or not slot_id:
            raise ValueError("contact slot IDs must be non-empty strings")
        mapping = _mapping(raw_slot, f"contact slot {slot_id}")
        _require_exact_keys(
            mapping,
            frozenset({"nodeIDs", "facePlaneAABB", "center"}),
            f"contact slot {slot_id}",
            frozenset({"outline"}),
        )
        node_ids = _string_sequence(mapping["nodeIDs"], f"contact slot {slot_id}.nodeIDs")
        if not node_ids or node_ids != sorted(node_ids) or node_ids != sorted(expected_by_slot[slot_id]):
            raise ValueError(f"contact slot {slot_id} nodeIDs must exactly match bound nodes")
        bounds_mapping = _mapping(mapping["facePlaneAABB"], f"contact slot {slot_id}.facePlaneAABB")
        _require_exact_keys(bounds_mapping, frozenset({"min", "max"}), f"contact slot {slot_id}.facePlaneAABB")
        face_bounds = FacePlaneAABB(
            min=_vector2_json(bounds_mapping["min"], f"contact slot {slot_id}.facePlaneAABB.min"),
            max=_vector2_json(bounds_mapping["max"], f"contact slot {slot_id}.facePlaneAABB.max"),
        )
        if any(face_bounds.min[axis] > face_bounds.max[axis] for axis in range(2)) or any(
            coordinate < 0 or coordinate > 1 for coordinate in (*face_bounds.min, *face_bounds.max)
        ):
            raise ValueError(f"contact slot {slot_id} facePlaneAABB must be normalized")
        center = _vector2_json(mapping["center"], f"contact slot {slot_id}.center")
        expected_center = (_midpoint(face_bounds.min[0], face_bounds.max[0]), _midpoint(face_bounds.min[1], face_bounds.max[1]))
        if center != expected_center:
            raise ValueError(f"contact slot {slot_id} center must derive from facePlaneAABB")
        outline: tuple[Vector2, ...] = ()
        if "outline" in mapping:
            outline = tuple(
                _vector2_json(point, f"contact slot {slot_id}.outline")
                for point in _sequence(mapping["outline"], f"contact slot {slot_id}.outline")
            )
            if len(outline) < 3:
                raise ValueError(f"contact slot {slot_id} outline needs at least three points")
            if any(
                coordinate < 0 or coordinate > 1
                for point in outline
                for coordinate in point
            ):
                raise ValueError(f"contact slot {slot_id} outline must be normalized")
            expected_bounds = FacePlaneAABB(
                min=(min(p[0] for p in outline), min(p[1] for p in outline)),
                max=(max(p[0] for p in outline), max(p[1] for p in outline)),
            )
            if face_bounds != expected_bounds:
                raise ValueError(f"contact slot {slot_id} facePlaneAABB must derive from its outline")
            if center != (
                _midpoint(expected_bounds.min[0], expected_bounds.max[0]),
                _midpoint(expected_bounds.min[1], expected_bounds.max[1]),
            ):
                raise ValueError(f"contact slot {slot_id} center must derive from its outline")
        parsed[slot_id] = ContactSlotDescriptorV2._from_validated(tuple(node_ids), face_bounds, center, outline)
    return parsed


def _mapping(value: object, field: str) -> Mapping[str, object]:
    if not isinstance(value, Mapping) or any(not isinstance(key, str) for key in value):
        raise ValueError(f"{field} must be an object")
    return value


def _sequence(value: object, field: str) -> Sequence[object]:
    if isinstance(value, (str, bytes)) or not isinstance(value, Sequence):
        raise ValueError(f"{field} must be an array")
    return value


def _string_sequence(value: object, field: str) -> list[str]:
    values = _sequence(value, field)
    if any(not isinstance(item, str) or not item for item in values):
        raise ValueError(f"{field} must contain non-empty strings")
    return list(values)  # type: ignore[return-value]


def _vector2_json(value: object, field: str) -> Vector2:
    values = _sequence(value, field)
    if len(values) != 2:
        raise ValueError(f"{field} must contain exactly two coordinates")
    return (_canonical_number(values[0], field), _canonical_number(values[1], field))


def _vector3_json(value: object, field: str) -> Vector3:
    values = _sequence(value, field)
    if len(values) != 3:
        raise ValueError(f"{field} must contain exactly three coordinates")
    return (
        _canonical_number(values[0], field),
        _canonical_number(values[1], field),
        _canonical_number(values[2], field),
    )


def _canonical_number(value: object, field: str) -> float:
    number = _finite_number(value, field)
    if _round(number) != number:
        raise ValueError(f"{field} must be rounded to nine decimals")
    return number
