from pathlib import Path
import json,hashlib
E=Path('.context/placid-badger-cad-second-half/pr-readiness-repair-2026-10-02/evo');p=E/'predecessor-attachment-normal-landscape'
f=next(p.glob('events-*.jsonl'));rows=[json.loads(l) for l in f.read_text().splitlines()];trans=json.loads((p/'transition-observations.json').read_text());workout=trans[0]['actualMutation']['sceneLifecycleToken'];ctors=[r for r in rows if r['event']=='board-scene-constructed'];predecessors=[r['sceneLifecycleToken'] for r in ctors if r['sceneLifecycleToken']!=workout];history=[]
for r in rows:
 if 'boardLifetimeCensus' not in r:continue
 for x in r['boardLifetimeCensus']:
  if x['sceneLifecycleToken'] not in predecessors:continue
  root,cam=x['root'],x['camera'];members=r.get('boardRenderMembership',{})
  history.append(dict(sequence=r['sequence'],epoch=r['epoch'],event=r['event'],recordScene=r.get('sceneLifecycleToken'),cachedMode=r.get('cachedMode'),cachedIDs=r.get('cachedIDs'),predecessor=x,workoutActualSceneAtRecord=members.get('rootRealitySceneID') if r.get('sceneLifecycleToken')==workout else None,attachedRootAndCamera=all(y.get('alive') and y.get('parentEntityID')!='nil' and y.get('realitySceneID')!='nil' for y in [root,cam]),bothActive=bool(root.get('isActive') and cam.get('isActive')),samePredecessorActualScene=root.get('realitySceneID')==cam.get('realitySceneID')))
points=[]
for t in trans:
 seq=t['actualMutation']['sequence'];h=[x for x in history if x['sequence']==seq];points.append(dict(phase=t['phaseIndex'],mode=t['mode'],actualMutationEpoch=t['actualMutation']['epoch'],observations=h))
tail=json.loads((p/'following-preview-tail.json').read_text())['record'];points.append(dict(phase='following-preview-tail',actualMutationEpoch=tail['epoch'],observations=[x for x in history if x['sequence']==tail['sequence']]))
checks=dict(weakCensusFlag=json.loads((p/'launch-review-environment.json').read_text()).get('HANGTEN_REVIEW_PREDECESSOR_ATTACHMENT_CENSUS')=='1',exactlyOnePredecessor=len(predecessors)==1,allFourBoundariesHaveOneObservation=all(len(x['observations'])==1 for x in points),constructedIdentityPreserved=all(x['predecessor']['root'].get('entityID')==x['predecessor']['constructedIDs']['rootID'] and x['predecessor']['camera'].get('entityID')==x['predecessor']['constructedIDs']['cameraID'] for x in history if x['predecessor']['root'].get('alive') and x['predecessor']['camera'].get('alive')))
r=dict(checks=checks,traceSHA256=hashlib.sha256(f.read_bytes()).hexdigest(),workoutToken=workout,constructors=ctors,predecessorTokens=predecessors,disappearRecords=[r for r in rows if r['event']=='view-disappear'],phaseAndTailObservations=points,fullPointHistory=history,summary=dict(observations=len(history),wrapperAliveObservations=sum(x['predecessor']['wrapperAlive'] for x in history),attachedObservations=sum(x['attachedRootAndCamera'] for x in history),bothActiveObservations=sum(x['bothActive'] for x in history)),limitations=['Point observations only; no inference about unobserved times or visible predecessor drawing.','Weak census does not own wrapper/root/camera. It adds no observation schedule or mutation.','A nonnil actual scene and isActive prove the recorded entity state, not an Apple framework root cause.'])
out=p/'predecessor-lifetime-analysis.json';assert not out.exists();out.write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(dict(checks=checks,summary=r['summary'],boundaries=[dict(phase=x['phase'],observations=[dict(wrapperAlive=y['predecessor']['wrapperAlive'],root=y['predecessor']['root'],camera=y['predecessor']['camera'],workoutScene=y['workoutActualSceneAtRecord']) for y in x['observations']]) for x in points]),indent=2));assert all(checks.values())
