import sys,json,hashlib
from pathlib import Path
import numpy as np
from pxr import Usd,UsdGeom
asset=Path(sys.argv[1]);out=Path(sys.argv[2]);stage=Usd.Stage.Open(str(asset));points=[];triangles=[];rows=[];offset=0;bad=[]
for prim in stage.Traverse():
 if not prim.IsA(UsdGeom.Mesh):continue
 m=UsdGeom.Mesh(prim);p=np.asarray(m.GetPointsAttr().Get(),dtype=float);n=np.asarray(m.GetNormalsAttr().Get(),dtype=float);idx=np.asarray(m.GetFaceVertexIndicesAttr().Get(),dtype=int).reshape(-1,3);mat=np.array(UsdGeom.Xformable(prim).ComputeLocalToWorldTransform(0));world=(np.c_[p,np.ones(len(p))]@mat)[:,:3];wn=n@np.linalg.inv(mat[:3,:3]).T;wn/=np.linalg.norm(wn,axis=1)[:,None];t=world[idx];flat=np.cross(t[:,1]-t[:,0],t[:,2]-t[:,0]);length=np.linalg.norm(flat,axis=1);valid=length>0;dot=np.einsum('ij,ikj->ik',flat[valid]/length[valid,None],wn[idx][valid]);negative=int(np.count_nonzero(dot< -1e-6));zero=int(np.count_nonzero(~valid));row={'node':prim.GetName(),'triangles':len(idx),'zeroAreaTriangles':zero,'normalCornersAgainstWinding':negative,'minimumNormalWindingCosine':float(dot.min()) if dot.size else None,'trianglesWithOpposingCornerNormal':int(np.count_nonzero(np.any(dot< -1e-6,axis=1))),'opposingCornerTriangleAreaMM2':float(length[valid][np.any(dot< -1e-6,axis=1)].sum()*5e5),'totalAreaMM2':float(length.sum()*5e5),'usdOrientation':str(m.GetOrientationAttr().Get())};negids=np.flatnonzero(valid)[np.any(dot< -1e-6,axis=1)];worst=sorted(negids,key=lambda i:length[i],reverse=True)[:20];row['largestOpposingNormalTriangles']=[{'triangle':int(i),'centerRuntimeM':t[i].mean(axis=0).tolist(),'areaMM2':float(length[i]*5e5),'cornerNormalWindingCosines':(wn[idx[i]]@(flat[i]/length[i])).tolist()} for i in worst];rows.append(row)
 if zero or negative:bad.append(row['node']+' degenerate triangle or inconsistent authored normal')
 points.append(world);triangles.append(idx+offset);offset+=len(world)
p=np.concatenate(points);t=np.concatenate(triangles);topology=[];boundary_diagnostics=None
for label,coordinates in [('exactStoredPositions',p),('rounded0.0001mm',np.round(p,7))]:
 unique,inverse=np.unique(coordinates,axis=0,return_inverse=True);faces=inverse[t];edges=np.concatenate([faces[:,[0,1]],faces[:,[1,2]],faces[:,[2,0]]]);undirected=np.sort(edges,axis=1);u,ei,count=np.unique(undirected,axis=0,return_inverse=True,return_counts=True);direction=np.where(edges[:,0]<edges[:,1],1,-1);balance=np.bincount(ei,weights=direction,minlength=len(u));boundary=int(np.count_nonzero(count==1));nonmanifold=int(np.count_nonzero(count>2));wrong=int(np.count_nonzero((count==2)&(balance!=0)));topology.append({'mode':label,'uniqueVertices':len(unique),'uniqueEdges':len(u),'boundaryEdges':boundary,'nonManifoldEdges':nonmanifold,'inconsistentPairedEdgeWinding':wrong,'watertight':boundary==0 and nonmanifold==0,'windingConsistentOnPairedEdges':wrong==0})
 if label=='exactStoredPositions':
  seg=unique[u[count==1]];vec=seg[:,1]-seg[:,0];seglen=np.linalg.norm(vec,axis=1);direction=vec/np.maximum(seglen[:,None],1e-30);distance_rows=[]
  for i in range(len(seg)):
   alignment=np.abs(direction@direction[i]);eligible=(alignment>.8)&(np.arange(len(seg))!=i);a=seg[eligible,0];v=vec[eligible];vv=np.einsum('ij,ij->i',v,v);samples=[]
   for fraction in [.1,.3,.5,.7,.9]:
    q=seg[i,0]+fraction*vec[i];t0=np.clip(np.einsum('ij,ij->i',q-a,v)/np.maximum(vv,1e-30),0,1);dist=np.linalg.norm(a+t0[:,None]*v-q,axis=1);samples.append(float(dist.min()*1000) if len(dist) else None)
   distance_rows.append({'startRuntimeM':seg[i,0].tolist(),'endRuntimeM':seg[i,1].tolist(),'lengthMM':float(seglen[i]*1000),'maxSampledNearestParallelBoundaryDistanceMM':max(samples) if all(x is not None for x in samples) else None})
  finite=[x for x in distance_rows if x['maxSampledNearestParallelBoundaryDistanceMM'] is not None];boundary_diagnostics={'method':'Five interior fractions per edge; nearest other boundary segment with abs(direction dot)>0.8. Diagnostic estimate of semantic seam spacing, not a certified global Hausdorff distance.','boundaryEdgeCount':len(seg),'totalBoundaryLengthMM':float(seglen.sum()*1000),'maximumSampledDistanceMM':max((x['maxSampledNearestParallelBoundaryDistanceMM'] for x in finite),default=None),'edgesAboveDeflection028MM':sum(x['maxSampledNearestParallelBoundaryDistanceMM']>.28 for x in finite),'worstEdges':sorted(finite,key=lambda x:x['maxSampledNearestParallelBoundaryDistanceMM'],reverse=True)[:20]}
r={'status':'pass' if not bad and topology[0]['watertight'] and topology[0]['windingConsistentOnPairedEdges'] else 'requires-review','blockingFindings':bad,'modelSHA256':hashlib.sha256(asset.read_bytes()).hexdigest(),'meshes':rows,'weldedWholeExportTopology':topology,'boundarySeamSpacing':boundary_diagnostics,'actualNativeEnvelopeXYZMM':((p.max(axis=0)-p.min(axis=0))[[0,2,1]]*1000).tolist(),'limits':['Exact-coordinate topology is reported independently of normals and material gates.','The secondary0.0001mm positional weld is diagnostic only; it does not repair or rewrite the model.','No triangle self-intersection/global manufacturing certificate is claimed.']};out.write_text(json.dumps(r,indent=2)+'\n');print(json.dumps({k:v for k,v in r.items() if k!='meshes'},indent=2))
