from pathlib import Path
import json,hashlib
E=Path('.context/placid-badger-cad-second-half/pr-readiness-repair-2026-10-02/evo')
def read(arm):
 p=E/('weak-hand-census-landscape' if arm=='O' else 'weak-hand-perspective-landscape');rows=[json.loads(l) for f in p.glob('events-*.jsonl') for l in f.read_bytes().splitlines()];trans=json.loads((p/'transition-observations.json').read_text());token=trans[0]['actualMutation']['sceneLifecycleToken'];host=json.loads((p/'normal-host-frame-validation.json').read_text());env=json.loads((p/'launch-review-environment.json').read_text())
 cpu=[r for r in rows if r.get('sceneLifecycleToken')==token and r.get('boardRenderMembership')]
 inputs={json.dumps(r['resolvedSurfaceInputs'],sort_keys=True) for r in rows if r.get('sceneLifecycleToken')==token and 'resolvedSurfaceInputs' in r}
 values={k:sorted({json.dumps(r.get(k),sort_keys=True) for r in cpu if k in r}) for k in ['rootTransform','cameraTransform']}
 values['projection']=sorted({json.dumps({k:r['boardRenderMembership'].get(k) for k in ['orthographic','perspective','near','far','verticalFOVDegrees']},sort_keys=True) for r in cpu})
 ctors=[r for r in rows if r['event']=='board-scene-constructed'];makes=[r for r in rows if r['event']=='view-make'];eventOrder=[r['event']+(':workout' if r.get('sceneLifecycleToken')==token else ':predecessor') for r in rows if r['event'] in ['board-scene-constructed','view-make','detach-trial-before','detach-trial-after','view-disappear']]
 handCtors=[r for r in rows if r['event']=='hand-lifecycle' and r['lifecycleEvent']=='constructor-entry']
 handRoles={r['handLifetimeToken']:i for i,r in enumerate(handCtors)}
 handPath=[dict(kind=r['handKind'],event=r['lifecycleEvent'],lifetimeOrdinal=handRoles[r['handLifetimeToken']]) for r in rows if r['event']=='hand-lifecycle']
 handCamera=[r for r in rows if r['event']=='hand-camera']
 handTransforms={kind:sorted({json.dumps(r['cameraTransform'],sort_keys=True) for r in handCamera if r['handKind']==kind}) for kind in ['single','pair']}
 viewEventOrder=[r['swiftUIEvent'] for r in rows if r['event']=='hand-view-lifecycle']
 return dict(handLifecyclePath=handPath,handCameraTransforms=handTransforms,handViewEventOrder=viewEventOrder,actualHandCameraRecords=handCamera,endpoints=host['normalOwnEndpoints'],inputs=sorted(inputs),values=values,environment=env,code=json.loads((p/'installed-binary-gate.json').read_text())['sha256'],constructorCount=len(ctors),makeCount=len(makes),eventOrder=eventOrder)
a,b=read('O'),read('P');ea=dict(a['environment']);eb=dict(b['environment']);ea.pop('HANGTEN_REVIEW_DIAGNOSTIC_RUN');eb.pop('HANGTEN_REVIEW_DIAGNOSTIC_RUN');eb.pop('HANGTEN_REVIEW_ALL_HAND_PERSPECTIVE')
checks=dict(sameObservedHandConstructorMakePath=a['handLifecyclePath']==b['handLifecyclePath'],sameRecordedHandCameraTransforms=a['handCameraTransforms']==b['handCameraTransforms'],sameCensusBinary=a['code']==b['code']=='70707e27453ae150763a302152c04e028564dbe97b41bffbcc91c98642f95c94',onlyPerspectiveGateAndRunIDEnvironmentDifference=ea==eb,sameNormalFrameEndpoints=a['endpoints']==b['endpoints'],sameResolvedWorkoutInputs=a['inputs']==b['inputs'],sameRootCameraTransformSets=a['values']==b['values'],sameConstructorAndMakeCounts=a['constructorCount']==b['constructorCount']==2 and a['makeCount']==b['makeCount']==2)
out=E/'weak-hand-projection-comparison.json';assert not out.exists();out.write_text(json.dumps(dict(checks=checks,orthographic=a,perspective=b,eventOrderingEqual=a['eventOrder']==b['eventOrder'],handViewEventOrderingEqual=a['handViewEventOrder']==b['handViewEventOrder'],limitations=['Entity/actual scene IDs naturally differ between fresh processes; compare role and recorded membership, not pointer equality across runs.','Frame endpoints and sampled path comparison do not assert identical animation timing.','Lifecycle paths compare actual observed constructor/make identities by ordinal, with no fixed historical hand count; SwiftUI event ordering is reported separately, not presenting-host evidence.','Hand projection and reset-fitted FOV intentionally differ from orthographic scale; same transforms do not imply identical foreshortening, apparent size or framing. Actual hand visibility and pose remain separate whole-image judgments.']),indent=2)+'\n');print(json.dumps(checks,indent=2));assert all(checks.values())
