var clock=LiveRopeSchedule()
precondition(clock.steps(elapsed:1.0/60)==4)
clock.accrue(elapsed:1.0/60)
clock.accrue(elapsed:1.0/60)
precondition(clock.takeSteps()==8,"RED busy elapsed was lost")
precondition(clock.takeSteps()==0,"RED debt was consumed twice")
clock.accrue(elapsed:100)
clock.accrue(elapsed:100)
precondition(clock.takeSteps()==8,"RED debt unbounded")
precondition(clock.takeSteps()==0)
clock.accrue(elapsed:1.0/480)
precondition(clock.takeSteps()==0)
clock.accrue(elapsed:1.0/480)
precondition(clock.takeSteps()==1)
clock.accrue(elapsed:1.0/60)
clock.pause();clock.accrue(elapsed:100);clock.resume()
precondition(clock.takeSteps()==0,"RED paused time/debt carried over")
clock.accrue(elapsed:.nan);clock.accrue(elapsed:.infinity);clock.accrue(elapsed:-1)
precondition(clock.takeSteps()==0)
clock.accrue(elapsed:1.0/60);clock.accept(settled:true)
precondition(clock.takeSteps()==0)
clock.setTarget(simd_quatd(angle:0.1,axis:SIMD3<Double>(0,0,1)))
clock.accrue(elapsed:1.0/60);precondition(clock.takeSteps()==4)
clock.stop();clock.resume();clock.setTarget(simd_quatd(angle:0.2,axis:SIMD3<Double>(0,0,1)))
clock.accrue(elapsed:100);precondition(clock.takeSteps()==0)
print("PASS bounded pending clock, once-only drain, invalid/pause/sleep/stop guards")
