from pathlib import Path
import json,sys,hashlib
base=Path('.context/placid-badger-cad-second-half/pr-readiness-repair-2026-10-02/evo');p=base/sys.argv[1]
h=json.loads((p/'hand-lifetime-validation.json').read_text());c=json.loads((p/'hand-camera-validation.json').read_text());controlH=json.loads((base/'all-hand-projection-o1-landscape/hand-lifetime-validation.json').read_text());controlC=json.loads((base/'all-hand-projection-o1-landscape/hand-camera-validation.json').read_text());caps=json.loads((p/'captures.json').read_text());trans=json.loads((p/'transition-observations.json').read_text());A=[232,143.33333333333331,410,70];B=[257,182.66666666666666,360,61.66666666666666];eps=1e-5
observations=[]
for r in h['boardFrameHistory']:
 for host in r['boardHosts']:
  frame=host['frameInWindow'];lam=(frame[2]-A[2])/(B[2]-A[2]);residual=max(abs(frame[i]-(A[i]+lam*(B[i]-A[i]))) for i in range(4));observations.append({'sequence':r['sequence'],'epoch':r['epoch'],'frame':frame,'lambda':lam,'maximumAffineResidualPoints':residual,'viewID':host['viewID'],'viewportPoints':r['viewportPoints']})
intermediates=[r for r in observations if r['frame'] not in [A,B]];post=[r for r in observations if r['epoch']>caps[0]['endEpoch']];firstpost=post[0] if post else None
sets=lambda rows,key:sorted({tuple(r[key]) for r in rows if r[key]})
checks={'observationsPresent':bool(observations),'exactCommonEndpoints':observations[0]['frame']==A and observations[-1]['frame']==B,'oneMatchingBoardARView':len({r['viewID'] for r in observations})==1,'sameAffineSegment':all(0<=r['lambda']<=1 and r['maximumAffineResidualPoints']<=eps for r in observations),'monotoneObservedProgress':all(observations[i+1]['lambda']>=observations[i]['lambda'] for i in range(len(observations)-1)),'intermediatesOnlyInitialActiveBeforeFirstCapture':all(trans[0]['actualMutation']['epoch']<=r['epoch']<caps[0]['startEpoch'] for r in intermediates),'firstPostCaptureCensusFinalByPlus1CaptureEnd':bool(firstpost) and firstpost['frame']==B and firstpost['epoch']<=caps[1]['endEpoch'],'allLaterFramesFinal':all(r['frame']==B for r in post),'boardRootTransformsEqual':sets(h['boardFrameHistory'],'rootTransform')==sets(controlH['boardFrameHistory'],'rootTransform'),'boardCameraTransformsEqual':sets(h['boardFrameHistory'],'cameraTransform')==sets(controlH['boardFrameHistory'],'cameraTransform'),'viewportEndpointValuesEqual':observations[0]['viewportPoints']==next(r['viewportPoints'] for r in controlH['boardFrameHistory'] if r['boardHosts']) and observations[-1]['viewportPoints']==controlH['boardFrameHistory'][-1]['viewportPoints'],'lifecycleCountsEqual':h['finalCounts']==controlH['finalCounts'],'creationOrderEqual':[(r['event'],r['detail'],r['kind']) for r in c['creationOrder']]==[(r['event'],r['detail'],r['kind']) for r in controlC['creationOrder']],'handCameraTransformsEqual':[r['cameraTransform'] for r in c['cameraRecords']]==[r['cameraTransform'] for r in controlC['cameraRecords']],'handDepthsEqual':[(r.get('minimumDepth'),r.get('maximumDepth'),r.get('framingVertexCount')) for r in c['cameraRecords']]==[(r.get('minimumDepth'),r.get('maximumDepth'),r.get('framingVertexCount')) for r in controlC['cameraRecords']]}
report={'checks':checks,'rule':'Root-authorized prospective endpoint/affine-path/semantic-window correspondence; original exact-set failure untouched.','observations':observations,'firstPostFirstCaptureCensus':firstpost,'limits':['No identical animation timing claim or assertion first screenshot settled.','Projection configuration includes initialization/workload timing.','Only sampled frames are evaluated; no claim about unobserved motion.']};out=p/'prospective-frame-correspondence.json';assert not out.exists();out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(checks,indent=2));assert all(checks.values())
