from pathlib import Path
import sys,json,hashlib,math
p=Path('.context/placid-badger-cad-second-half/pr-readiness-repair-2026-10-02/evo')/sys.argv[1]
rows=[json.loads(l) for f in p.glob('events-*.jsonl') for l in f.read_text().splitlines()]
env=json.loads((p/'launch-review-environment.json').read_text());perspective=env.get('HANGTEN_REVIEW_ALL_HAND_PERSPECTIVE')=='1'
cameras=[r for r in rows if r['event']=='hand-camera'];configured=[r for r in cameras if r['cameraEvent']=='configured'];fits=[r for r in cameras if r['cameraEvent']=='reset-fitted'];life=[r for r in rows if r['event']=='hand-lifecycle']
constructors=[r for r in life if r['lifecycleEvent']=='constructor-entry']
checks={'openingFlag':rows[0]['usesPerspectiveHandCameras']==perspective,'suppressionAbsent':'HANGTEN_REVIEW_SUPPRESS_ALL_HAND_HOSTS' not in env and not rows[0]['suppressesAllHandHosts'],'cameraEvidencePresent':bool(configured) and bool(fits),'everyConfiguredCameraHasReset':{r['handCameraID'] for r in configured}<={r['handCameraID'] for r in fits},'oneConfiguredCameraPerConstructedScene':len(configured)==len(constructors),'componentMatchesFlag':all(r['perspectivePresent']==perspective and r['orthographicPresent']!=perspective for r in cameras),'noFitRejected':not any(r['cameraEvent']=='fit-rejected' for r in cameras),'unchangedClips':all(abs(r['near']-.1)<1e-6 and r['far']==100 for r in cameras),'finiteDepthsInsideClips':all(r['allDepthsFinite'] and r['allDepthsInsideUnchangedClips'] and r['framingVertexCount']>0 for r in fits),'validFOVorScale':all(0<r['fieldOfViewInDegrees']<180 and 'vertical' in r['fieldOfViewOrientation'].lower() if perspective else r['orthographicScale']>0 for r in fits)}
order=[{'event':r['event'],'detail':r.get('lifecycleEvent') or r.get('cameraEvent') or r.get('cachedMode'),'kind':r.get('handKind'),'sequence':r['sequence'],'epoch':r['epoch']} for r in rows if r['event'] in ['hand-lifecycle','hand-camera','view-make']]
report={'checks':checks,'perspective':perspective,'configuredCameraCount':len(configured),'observedKinds':sorted({r['handKind'] for r in configured}),'cameraRecords':cameras,'creationOrder':order,'limits':['Only actually constructed scenes have runtime camera evidence; unconstructed single-hand path is not runtime exercised.','No gestures used; orbit behavior is source-reviewed only.','Perspective preserves camera transform and fits geometry with1.08 margin; projected appearance is not photometrically identical.']}
f=p/'hand-camera-validation.json';assert not f.exists();f.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'checks':checks,'configuredCameraCount':len(configured),'observedKinds':report['observedKinds']},indent=2));assert all(checks.values())
